<%@ Page Title="" Language="C#" MasterPageFile="~/JavaScript.Master" AutoEventWireup="true" CodeBehind="JavaScript Where To.aspx.cs" Inherits="Project.JavaScript_Where_To" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="ContentPlaceHolder2" runat="server">
   
    <h1 style="box-sizing: inherit; font-size: 42px; font-family: &quot;Segoe UI&quot;, Arial, sans-serif; font-weight: 400; margin: 10px 0px; color: rgb(0, 0, 0); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">JavaScript<span>&nbsp;</span><span class="color_h1" style="box-sizing: inherit;">Where To</span></h1>
   
</asp:Content>
<asp:Content ID="Content4" ContentPlaceHolderID="ContentPlaceHolder3" runat="server">
    
    <h2 style="box-sizing: inherit; font-size: 32px; font-family: &quot;Segoe UI&quot;, Arial, sans-serif; font-weight: 400; margin: 10px 0px; color: rgb(0, 0, 0); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">The &lt;script&gt; Tag</h2>
    <p style="box-sizing: inherit; margin-top: 1.2em; margin-bottom: 1.2em; font-size: 15px; color: rgb(0, 0, 0); font-family: Verdana, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        In HTML, JavaScript code is inserted between<span>&nbsp;</span><code class="w3-codespan" style="box-sizing: inherit; font-family: Consolas, &quot;courier new&quot;; font-size: 15.75px; color: crimson; background-color: rgba(222, 222, 222, 0.3); padding-left: 4px; padding-right: 4px;">&lt;script&gt;</code><span>&nbsp;</span>and<span>&nbsp;</span><code class="w3-codespan" style="box-sizing: inherit; font-family: Consolas, &quot;courier new&quot;; font-size: 15.75px; color: crimson; background-color: rgba(222, 222, 222, 0.3); padding-left: 4px; padding-right: 4px;">&lt;/script&gt;</code><span>&nbsp;</span>tags.</p>
    <div class="w3-example" style="box-sizing: inherit; background-color: rgb(241, 241, 241); padding: 8px 20px; margin: 24px -20px; box-shadow: none !important; color: rgb(0, 0, 0); font-family: Verdana, sans-serif; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        <h3 style="box-sizing: inherit; font-size: 24px; font-family: &quot;Segoe UI&quot;, Arial, sans-serif; font-weight: 400; margin: 10px 0px;">Example</h3>
        <div class="w3-code notranslate htmlHigh" style="box-sizing: inherit; font-family: Consolas, &quot;courier new&quot;; font-size: 15px; width: auto; background-color: rgb(255, 255, 255); padding: 8px 12px; border-left: 4px solid rgb(76, 175, 80); overflow-wrap: break-word; margin-top: 16px !important; margin-bottom: 16px !important;">
            <span class="tagnamecolor" style="box-sizing: inherit; color: brown;"><span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&lt;</span>script<span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&gt;</span></span><span class="jscolor" style="box-sizing: inherit; color: black;"><br style="box-sizing: inherit;" />
            document.<span class="jspropertycolor" style="box-sizing: inherit; color: black;">getElementById</span>(<span class="jsstringcolor" style="box-sizing: inherit; color: brown;">&quot;demo&quot;</span>).<span class="jspropertycolor" style="box-sizing: inherit; color: black;">innerHTML</span><span>&nbsp;</span>=<span>&nbsp;</span><span class="jsstringcolor" style="box-sizing: inherit; color: brown;">&quot;My First JavaScript&quot;</span>;<br style="box-sizing: inherit;" />
            </span><span class="tagnamecolor" style="box-sizing: inherit; color: brown;"><span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&lt;</span>/script<span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&gt;</span></span></div>
    </div>
    <h2 style="box-sizing: inherit; font-size: 32px; font-family: &quot;Segoe UI&quot;, Arial, sans-serif; font-weight: 400; margin: 10px 0px; color: rgb(0, 0, 0); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">The &lt;script&gt; Tag</h2>
    <p style="box-sizing: inherit; margin-top: 1.2em; margin-bottom: 1.2em; font-size: 15px; color: rgb(0, 0, 0); font-family: Verdana, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        In HTML, JavaScript code is inserted between<span>&nbsp;</span><code class="w3-codespan" style="box-sizing: inherit; font-family: Consolas, &quot;courier new&quot;; font-size: 15.75px; color: crimson; background-color: rgba(222, 222, 222, 0.3); padding-left: 4px; padding-right: 4px;">&lt;script&gt;</code><span>&nbsp;</span>and<span>&nbsp;</span><code class="w3-codespan" style="box-sizing: inherit; font-family: Consolas, &quot;courier new&quot;; font-size: 15.75px; color: crimson; background-color: rgba(222, 222, 222, 0.3); padding-left: 4px; padding-right: 4px;">&lt;/script&gt;</code><span>&nbsp;</span>tags.</p>
    <div class="w3-example" style="box-sizing: inherit; background-color: rgb(241, 241, 241); padding: 8px 20px; margin: 24px -20px; box-shadow: none !important; color: rgb(0, 0, 0); font-family: Verdana, sans-serif; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        <h3 style="box-sizing: inherit; font-size: 24px; font-family: &quot;Segoe UI&quot;, Arial, sans-serif; font-weight: 400; margin: 10px 0px;">Example</h3>
        <div class="w3-code notranslate htmlHigh" style="box-sizing: inherit; font-family: Consolas, &quot;courier new&quot;; font-size: 15px; width: auto; background-color: rgb(255, 255, 255); padding: 8px 12px; border-left: 4px solid rgb(76, 175, 80); overflow-wrap: break-word; margin-top: 16px !important; margin-bottom: 16px !important;">
            <span class="tagnamecolor" style="box-sizing: inherit; color: brown;"><span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&lt;</span>script<span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&gt;</span></span><span class="jscolor" style="box-sizing: inherit; color: black;"><br style="box-sizing: inherit;" />
            document.<span class="jspropertycolor" style="box-sizing: inherit; color: black;">getElementById</span>(<span class="jsstringcolor" style="box-sizing: inherit; color: brown;">&quot;demo&quot;</span>).<span class="jspropertycolor" style="box-sizing: inherit; color: black;">innerHTML</span><span>&nbsp;</span>=<span>&nbsp;</span><span class="jsstringcolor" style="box-sizing: inherit; color: brown;">&quot;My First JavaScript&quot;</span>;<br style="box-sizing: inherit;" />
            </span><span class="tagnamecolor" style="box-sizing: inherit; color: brown;"><span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&lt;</span>/script<span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&gt;</span></span></div>
    </div>
    <h1 style="box-sizing: inherit; font-size: 42px; font-family: &quot;Segoe UI&quot;, Arial, sans-serif; font-weight: 400; margin: 10px 0px; color: rgb(0, 0, 0); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        <span style="color: rgb(0, 0, 0); font-family: Verdana, sans-serif; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 204); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">Old JavaScript examples may use a type attribute: &lt;script type=&quot;text/javascript&quot;&gt;.</span><br style="box-sizing: inherit; color: rgb(0, 0, 0); font-family: Verdana, sans-serif; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 204); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;" />
        <span style="color: rgb(0, 0, 0); font-family: Verdana, sans-serif; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 204); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">The type attribute is not required. JavaScript is the default scripting language in HTML.</span></h1>
    <h2 style="box-sizing: inherit; font-size: 32px; font-family: &quot;Segoe UI&quot;, Arial, sans-serif; font-weight: 400; margin: 10px 0px; color: rgb(0, 0, 0); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">JavaScript Functions and Events</h2>
    <p style="box-sizing: inherit; margin-top: 1.2em; margin-bottom: 1.2em; font-size: 15px; color: rgb(0, 0, 0); font-family: Verdana, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        A JavaScript<span>&nbsp;</span><code class="w3-codespan" style="box-sizing: inherit; font-family: Consolas, &quot;courier new&quot;; font-size: 15.75px; color: crimson; background-color: rgba(222, 222, 222, 0.3); padding-left: 4px; padding-right: 4px;">function</code><span>&nbsp;</span>is a block of JavaScript code, that can be executed when &quot;called&quot; for.</p>
    <p style="box-sizing: inherit; margin-top: 1.2em; margin-bottom: 1.2em; font-size: 15px; color: rgb(0, 0, 0); font-family: Verdana, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        For example, a function can be called when an<span>&nbsp;</span><b style="box-sizing: inherit; font-weight: bolder;">event</b><span>&nbsp;</span>occurs, like when the user clicks a button.</p>
    <div class="w3-panel w3-note" style="box-sizing: inherit; padding: 16px 32px;  background-color: rgb(255, 255, 204); border-left: none; color: rgb(0, 0, 0); font-family: Verdana, sans-serif; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        <p style="box-sizing: inherit; margin-top: 1em; margin-bottom: 1em; font-size: 15px;">
            You will learn much more about functions and events in later chapters.</p>
    </div>
    <hr style="box-sizing: content-box; height: 0px; overflow: visible; border-width: 1px 0px 0px; border-right-style: initial; border-bottom-style: initial; border-left-style: initial; border-right-color: initial; border-bottom-color: initial; border-left-color: initial; border-image: initial; border-top-style: solid; border-top-color: rgb(238, 238, 238); margin: 20px -16px; color: rgb(0, 0, 0); font-family: Verdana, sans-serif; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;" />
    <h2 style="box-sizing: inherit; font-size: 32px; font-family: &quot;Segoe UI&quot;, Arial, sans-serif; font-weight: 400; margin: 10px 0px; color: rgb(0, 0, 0); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">JavaScript in &lt;head&gt; or &lt;body&gt;</h2>
    <p style="box-sizing: inherit; margin-top: 1.2em; margin-bottom: 1.2em; font-size: 15px; color: rgb(0, 0, 0); font-family: Verdana, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        You can place any number of scripts in an HTML document.</p>
    <p style="box-sizing: inherit; margin-top: 1.2em; margin-bottom: 1.2em; font-size: 15px; color: rgb(0, 0, 0); font-family: Verdana, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        Scripts can be placed in the<span>&nbsp;</span><code class="w3-codespan" style="box-sizing: inherit; font-family: Consolas, &quot;courier new&quot;; font-size: 15.75px; color: crimson; background-color: rgba(222, 222, 222, 0.3); padding-left: 4px; padding-right: 4px;">&lt;body&gt;</code>, or in the<span>&nbsp;</span><code class="w3-codespan" style="box-sizing: inherit; font-family: Consolas, &quot;courier new&quot;; font-size: 15.75px; color: crimson; background-color: rgba(222, 222, 222, 0.3); padding-left: 4px; padding-right: 4px;">&lt;head&gt;</code><span>&nbsp;</span>section of an HTML page, or in both.</p>
    <hr style="box-sizing: content-box; height: 0px; overflow: visible; border-width: 1px 0px 0px; border-right-style: initial; border-bottom-style: initial; border-left-style: initial; border-right-color: initial; border-bottom-color: initial; border-left-color: initial; border-image: initial; border-top-style: solid; border-top-color: rgb(238, 238, 238); margin: 20px -16px; color: rgb(0, 0, 0); font-family: Verdana, sans-serif; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;" />
    <h2 style="box-sizing: inherit; font-size: 32px; font-family: &quot;Segoe UI&quot;, Arial, sans-serif; font-weight: 400; margin: 10px 0px; color: rgb(0, 0, 0); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">JavaScript in &lt;head&gt;</h2>
    <p style="box-sizing: inherit; margin-top: 1.2em; margin-bottom: 1.2em; font-size: 15px; color: rgb(0, 0, 0); font-family: Verdana, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        In this example, a JavaScript<span>&nbsp;</span><code class="w3-codespan" style="box-sizing: inherit; font-family: Consolas, &quot;courier new&quot;; font-size: 15.75px; color: crimson; background-color: rgba(222, 222, 222, 0.3); padding-left: 4px; padding-right: 4px;">function</code><span>&nbsp;</span>is placed in the<span>&nbsp;</span><code class="w3-codespan" style="box-sizing: inherit; font-family: Consolas, &quot;courier new&quot;; font-size: 15.75px; color: crimson; background-color: rgba(222, 222, 222, 0.3); padding-left: 4px; padding-right: 4px;">&lt;head&gt;</code><span>&nbsp;</span>section of an HTML page.</p>
    <p style="box-sizing: inherit; margin-top: 1.2em; margin-bottom: 1.2em; font-size: 15px; color: rgb(0, 0, 0); font-family: Verdana, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        The function is invoked (called) when a button is clicked:</p>
    <div class="w3-example" style="box-sizing: inherit; background-color: rgb(241, 241, 241); padding: 8px 20px; margin: 24px -20px; box-shadow: none !important; color: rgb(0, 0, 0); font-family: Verdana, sans-serif; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        <h3 style="box-sizing: inherit; font-size: 24px; font-family: &quot;Segoe UI&quot;, Arial, sans-serif; font-weight: 400; margin: 10px 0px;">Example</h3>
        <div class="w3-code notranslate htmlHigh" style="box-sizing: inherit; font-family: Consolas, &quot;courier new&quot;; font-size: 15px; width: auto; background-color: rgb(255, 255, 255); padding: 8px 12px; border-left: 4px solid rgb(76, 175, 80); overflow-wrap: break-word; margin-top: 16px !important; margin-bottom: 16px !important;">
            <span class="tagnamecolor" style="box-sizing: inherit; color: brown;"><span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&lt;</span>!DOCTYPE<span class="attributecolor" style="box-sizing: inherit; color: red;"><span>&nbsp;</span>html</span><span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&gt;</span></span><br style="box-sizing: inherit;" />
            <span class="tagnamecolor" style="box-sizing: inherit; color: brown;"><span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&lt;</span>html<span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&gt;</span></span><p style="box-sizing: inherit; margin-top: 1em; margin-bottom: 1em; font-size: 15px;">
                <span class="tagnamecolor" style="box-sizing: inherit; color: brown;"><span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&lt;</span>head<span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&gt;</span></span><br style="box-sizing: inherit;" />
                <span class="tagnamecolor" style="box-sizing: inherit; color: brown;"><span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&lt;</span>script<span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&gt;</span></span><span class="jscolor" style="box-sizing: inherit; color: black;"><br style="box-sizing: inherit;" />
                <span class="jskeywordcolor" style="box-sizing: inherit; color: mediumblue;">function</span><span>&nbsp;</span>myFunction() {<br style="box-sizing: inherit;" />
                <span class="jsnumbercolor" style="box-sizing: inherit; color: red;"></span>&nbsp;&nbsp;document.<span class="jspropertycolor" style="box-sizing: inherit; color: black;">getElementById</span>(<span class="jsstringcolor" style="box-sizing: inherit; color: brown;">&quot;demo&quot;</span>).<span class="jspropertycolor" style="box-sizing: inherit; color: black;">innerHTML</span><span>&nbsp;</span>=<span>&nbsp;</span><span class="jsstringcolor" style="box-sizing: inherit; color: brown;">&quot;Paragraph changed.&quot;</span>;<br style="box-sizing: inherit;" />
                <span class="jsnumbercolor" style="box-sizing: inherit; color: red;"></span>}<br style="box-sizing: inherit;" />
                </span><span class="tagnamecolor" style="box-sizing: inherit; color: brown;"><span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&lt;</span>/script<span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&gt;</span></span><br style="box-sizing: inherit;" />
                <span class="tagnamecolor" style="box-sizing: inherit; color: brown;"><span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&lt;</span>/head<span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&gt;</span></span><br style="box-sizing: inherit;" />
                <span class="tagnamecolor" style="box-sizing: inherit; color: brown;"><span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&lt;</span>body<span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&gt;</span></span></p>
            <p style="box-sizing: inherit; margin-top: 1em; margin-bottom: 1em; font-size: 15px;">
                <span class="tagnamecolor" style="box-sizing: inherit; color: brown;"><span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&lt;</span>h1<span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&gt;</span></span>A Web Page<span class="tagnamecolor" style="box-sizing: inherit; color: brown;"><span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&lt;</span>/h1<span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&gt;</span></span><br style="box-sizing: inherit;" />
                <span class="tagnamecolor" style="box-sizing: inherit; color: brown;"><span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&lt;</span>p<span class="attributecolor" style="box-sizing: inherit; color: red;"><span>&nbsp;</span>id<span class="attributevaluecolor" style="box-sizing: inherit; color: mediumblue;">=&quot;demo&quot;</span></span><span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&gt;</span></span>A Paragraph<span class="tagnamecolor" style="box-sizing: inherit; color: brown;"><span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&lt;</span>/p<span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&gt;</span></span><br style="box-sizing: inherit;" />
                <span class="tagnamecolor" style="box-sizing: inherit; color: brown;"><span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&lt;</span>button<span class="attributecolor" style="box-sizing: inherit; color: red;"><span>&nbsp;</span>type<span class="attributevaluecolor" style="box-sizing: inherit; color: mediumblue;">=&quot;button&quot;</span><span>&nbsp;</span>onclick<span class="attributevaluecolor" style="box-sizing: inherit; color: mediumblue;">=&quot;myFunction()&quot;</span></span><span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&gt;</span></span>Try it<span class="tagnamecolor" style="box-sizing: inherit; color: brown;"><span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&lt;</span>/button<span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&gt;</span></span></p>
            <p style="box-sizing: inherit; margin-top: 1em; margin-bottom: 1em; font-size: 15px;">
                <span class="tagnamecolor" style="box-sizing: inherit; color: brown;"><span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&lt;</span>/body<span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&gt;</span></span><br style="box-sizing: inherit;" />
                <span class="tagnamecolor" style="box-sizing: inherit; color: brown;"><span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&lt;</span>/html<span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&gt;</span></span></p>
        </div>
    </div>
    <p style="box-sizing: inherit; font-size: 42px; font-family: &quot;Segoe UI&quot;, Arial, sans-serif; font-weight: 400; margin: 10px 0px; color: rgb(0, 0, 0); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        &nbsp;</p>
    
</asp:Content>
