<%@ Page Title="" Language="C#" MasterPageFile="~/JavaScript.Master" AutoEventWireup="true" CodeBehind="JavaScript Output.aspx.cs" Inherits="Project.JavaScript_Output" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="ContentPlaceHolder2" runat="server">
    <h1 style="box-sizing: inherit; font-size: 42px; font-family: &quot;Segoe UI&quot;, Arial, sans-serif; font-weight: 400; margin: 10px 0px; color: rgb(0, 0, 0); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">JavaScript<span>&nbsp;</span><span class="color_h1" style="box-sizing: inherit;">Output</span></h1>
</asp:Content>
<asp:Content ID="Content4" ContentPlaceHolderID="ContentPlaceHolder3" runat="server">
    <h2 style="box-sizing: inherit; font-size: 32px; font-family: &quot;Segoe UI&quot;, Arial, sans-serif; font-weight: 400; margin: 10px 0px; color: rgb(0, 0, 0); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">JavaScript Display Possibilities</h2>
    <p style="box-sizing: inherit; margin-top: 1.2em; margin-bottom: 1.2em; font-size: 15px; color: rgb(0, 0, 0); font-family: Verdana, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        JavaScript can &quot;display&quot; data in different ways:</p>
    <ul style="box-sizing: inherit; color: rgb(0, 0, 0); font-family: Verdana, sans-serif; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        <li style="box-sizing: inherit;">Writing into an HTML element, using<span>&nbsp;</span><code class="w3-codespan" style="box-sizing: inherit; font-family: Consolas, &quot;courier new&quot;; font-size: 15.75px; color: crimson; background-color: rgba(222, 222, 222, 0.3); padding-left: 4px; padding-right: 4px;">innerHTML</code>.</li>
        <li style="box-sizing: inherit;">Writing into the HTML output using<span>&nbsp;</span><code class="w3-codespan" style="box-sizing: inherit; font-family: Consolas, &quot;courier new&quot;; font-size: 15.75px; color: crimson; background-color: rgba(222, 222, 222, 0.3); padding-left: 4px; padding-right: 4px;">document.write()</code>.</li>
        <li style="box-sizing: inherit;">Writing into an alert box, using<span>&nbsp;</span><code class="w3-codespan" style="box-sizing: inherit; font-family: Consolas, &quot;courier new&quot;; font-size: 15.75px; color: crimson; background-color: rgba(222, 222, 222, 0.3); padding-left: 4px; padding-right: 4px;">window.alert()</code>.</li>
        <li style="box-sizing: inherit;">Writing into the browser console, using<span>&nbsp;</span><code class="w3-codespan" style="box-sizing: inherit; font-family: Consolas, &quot;courier new&quot;; font-size: 15.75px; color: crimson; background-color: rgba(222, 222, 222, 0.3); padding-left: 4px; padding-right: 4px;">console.log()</code>.</li>
    </ul>
    <hr style="box-sizing: content-box; height: 0px; overflow: visible; border-width: 1px 0px 0px; border-right-style: initial; border-bottom-style: initial; border-left-style: initial; border-right-color: initial; border-bottom-color: initial; border-left-color: initial; border-image: initial; border-top-style: solid; border-top-color: rgb(238, 238, 238); margin: 20px -16px; color: rgb(0, 0, 0); font-family: Verdana, sans-serif; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;" />
    <h2 style="box-sizing: inherit; font-size: 32px; font-family: &quot;Segoe UI&quot;, Arial, sans-serif; font-weight: 400; margin: 10px 0px; color: rgb(0, 0, 0); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Using innerHTML</h2>
    <p style="box-sizing: inherit; margin-top: 1.2em; margin-bottom: 1.2em; font-size: 15px; color: rgb(0, 0, 0); font-family: Verdana, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        To access an HTML element, JavaScript can use the<span>&nbsp;</span><code class="w3-codespan" style="box-sizing: inherit; font-family: Consolas, &quot;courier new&quot;; font-size: 15.75px; color: crimson; background-color: rgba(222, 222, 222, 0.3); padding-left: 4px; padding-right: 4px;">document.getElementById(id)</code><span>&nbsp;</span>method.</p>
    <p style="box-sizing: inherit; margin-top: 1.2em; margin-bottom: 1.2em; font-size: 15px; color: rgb(0, 0, 0); font-family: Verdana, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        The<span>&nbsp;</span><code class="w3-codespan" style="box-sizing: inherit; font-family: Consolas, &quot;courier new&quot;; font-size: 15.75px; color: crimson; background-color: rgba(222, 222, 222, 0.3); padding-left: 4px; padding-right: 4px;">id</code><span>&nbsp;</span>attribute defines the HTML element. The<span>&nbsp;</span><code class="w3-codespan" style="box-sizing: inherit; font-family: Consolas, &quot;courier new&quot;; font-size: 15.75px; color: crimson; background-color: rgba(222, 222, 222, 0.3); padding-left: 4px; padding-right: 4px;">innerHTML</code><span>&nbsp;</span>property defines the HTML content:</p>
    <div class="w3-example" style="box-sizing: inherit; background-color: rgb(241, 241, 241); padding: 8px 20px; margin: 24px -20px; box-shadow: none !important; color: rgb(0, 0, 0); font-family: Verdana, sans-serif; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        <h3 style="box-sizing: inherit; font-size: 24px; font-family: &quot;Segoe UI&quot;, Arial, sans-serif; font-weight: 400; margin: 10px 0px;">Example</h3>
        <div class="w3-code notranslate htmlHigh" style="box-sizing: inherit; font-family: Consolas, &quot;courier new&quot;; font-size: 15px; width: auto; background-color: rgb(255, 255, 255); padding: 8px 12px; border-left: 4px solid rgb(76, 175, 80); overflow-wrap: break-word; margin-top: 16px !important; margin-bottom: 16px !important;">
            <span class="tagnamecolor" style="box-sizing: inherit; color: brown;"><span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&lt;</span>!DOCTYPE<span class="attributecolor" style="box-sizing: inherit; color: red;"><span>&nbsp;</span>html</span><span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&gt;</span></span><br style="box-sizing: inherit;" />
            <span class="tagnamecolor" style="box-sizing: inherit; color: brown;"><span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&lt;</span>html<span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&gt;</span></span><br style="box-sizing: inherit;" />
            <span class="tagnamecolor" style="box-sizing: inherit; color: brown;"><span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&lt;</span>body<span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&gt;</span></span><br style="box-sizing: inherit;" />
            <br style="box-sizing: inherit;" />
            <span class="tagnamecolor" style="box-sizing: inherit; color: brown;"><span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&lt;</span>h1<span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&gt;</span></span>My First Web Page<span class="tagnamecolor" style="box-sizing: inherit; color: brown;"><span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&lt;</span>/h1<span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&gt;</span></span><br style="box-sizing: inherit;" />
            <span class="tagnamecolor" style="box-sizing: inherit; color: brown;"><span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&lt;</span>p<span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&gt;</span></span>My First Paragraph<span class="tagnamecolor" style="box-sizing: inherit; color: brown;"><span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&lt;</span>/p<span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&gt;</span></span><br style="box-sizing: inherit;" />
            <br style="box-sizing: inherit;" />
            <span class="tagnamecolor" style="box-sizing: inherit; color: brown;"><span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&lt;</span>p<span class="attributecolor" style="box-sizing: inherit; color: red;"><span>&nbsp;</span>id<span class="attributevaluecolor" style="box-sizing: inherit; color: mediumblue;">=&quot;demo&quot;</span></span><span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&gt;&lt;</span>/p<span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&gt;</span></span><br style="box-sizing: inherit;" />
            <br style="box-sizing: inherit;" />
            <span class="tagnamecolor" style="box-sizing: inherit; color: brown;"><span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&lt;</span>script<span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&gt;</span></span><span class="jscolor" style="box-sizing: inherit; color: black;"><br style="box-sizing: inherit;" />
            <span class="jsnumbercolor" style="box-sizing: inherit; color: red;"></span>document.<span class="jspropertycolor" style="box-sizing: inherit; color: black;">getElementById</span>(<span class="jsstringcolor" style="box-sizing: inherit; color: brown;">&quot;demo&quot;</span>).<span class="jspropertycolor" style="box-sizing: inherit; color: black;">innerHTML</span><span>&nbsp;</span>=<span>&nbsp;</span><span class="jsnumbercolor" style="box-sizing: inherit; color: red;">5</span><span>&nbsp;</span>+<span>&nbsp;</span><span class="jsnumbercolor" style="box-sizing: inherit; color: red;">6</span>;<br style="box-sizing: inherit;" />
            <span class="jsnumbercolor" style="box-sizing: inherit; color: red;"></span></span><span class="tagnamecolor" style="box-sizing: inherit; color: brown;"><span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&lt;</span>/script<span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&gt;</span></span><br style="box-sizing: inherit;" />
            <br style="box-sizing: inherit;" />
            <span class="tagnamecolor" style="box-sizing: inherit; color: brown;"><span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&lt;</span>/body<span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&gt;</span></span><br style="box-sizing: inherit;" />
            <span class="tagnamecolor" style="box-sizing: inherit; color: brown;"><span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&lt;</span>/html<span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&gt;</span></span></div>
    </div>
    <div class="w3-panel w3-note" style="box-sizing: inherit; padding: 16px 32px; background-color: rgb(255, 255, 204); border-left: none; color: rgb(0, 0, 0); font-family: Verdana, sans-serif; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        <p style="box-sizing: inherit; margin-top: 1em; margin-bottom: 1em; font-size: 15px;">
            Changing the innerHTML property of an HTML element is a common way to display data in HTML.</p>
    </div>
    <hr style="box-sizing: content-box; height: 0px; overflow: visible; border-width: 1px 0px 0px; border-right-style: initial; border-bottom-style: initial; border-left-style: initial; border-right-color: initial; border-bottom-color: initial; border-left-color: initial; border-image: initial; border-top-style: solid; border-top-color: rgb(238, 238, 238); margin: 20px -16px; color: rgb(0, 0, 0); font-family: Verdana, sans-serif; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;" />
    <h2 style="box-sizing: inherit; font-size: 32px; font-family: &quot;Segoe UI&quot;, Arial, sans-serif; font-weight: 400; margin: 10px 0px; color: rgb(0, 0, 0); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Using document.write()</h2>
    <p style="box-sizing: inherit; margin-top: 1.2em; margin-bottom: 1.2em; font-size: 15px; color: rgb(0, 0, 0); font-family: Verdana, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        For testing purposes, it is convenient to use<span>&nbsp;</span><code class="w3-codespan" style="box-sizing: inherit; font-family: Consolas, &quot;courier new&quot;; font-size: 15.75px; color: crimson; background-color: rgba(222, 222, 222, 0.3); padding-left: 4px; padding-right: 4px;">document.write()</code>:</p>
    <div class="w3-example" style="box-sizing: inherit; background-color: rgb(241, 241, 241); padding: 8px 20px; margin: 24px -20px; box-shadow: none !important; color: rgb(0, 0, 0); font-family: Verdana, sans-serif; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        <h3 style="box-sizing: inherit; font-size: 24px; font-family: &quot;Segoe UI&quot;, Arial, sans-serif; font-weight: 400; margin: 10px 0px;">Example</h3>
        <div class="w3-code notranslate htmlHigh" style="box-sizing: inherit; font-family: Consolas, &quot;courier new&quot;; font-size: 15px; width: auto; background-color: rgb(255, 255, 255); padding: 8px 12px; border-left: 4px solid rgb(76, 175, 80); overflow-wrap: break-word; margin-top: 16px !important; margin-bottom: 16px !important;">
            <span class="tagnamecolor" style="box-sizing: inherit; color: brown;"><span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&lt;</span>!DOCTYPE<span class="attributecolor" style="box-sizing: inherit; color: red;"><span>&nbsp;</span>html</span><span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&gt;</span></span><br style="box-sizing: inherit;" />
            <span class="tagnamecolor" style="box-sizing: inherit; color: brown;"><span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&lt;</span>html<span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&gt;</span></span><br style="box-sizing: inherit;" />
            <span class="tagnamecolor" style="box-sizing: inherit; color: brown;"><span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&lt;</span>body<span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&gt;</span></span><br style="box-sizing: inherit;" />
            <br style="box-sizing: inherit;" />
            <span class="tagnamecolor" style="box-sizing: inherit; color: brown;"><span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&lt;</span>h1<span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&gt;</span></span>My First Web Page<span class="tagnamecolor" style="box-sizing: inherit; color: brown;"><span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&lt;</span>/h1<span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&gt;</span></span><br style="box-sizing: inherit;" />
            <span class="tagnamecolor" style="box-sizing: inherit; color: brown;"><span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&lt;</span>p<span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&gt;</span></span>My first paragraph.<span class="tagnamecolor" style="box-sizing: inherit; color: brown;"><span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&lt;</span>/p<span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&gt;</span></span><br style="box-sizing: inherit;" />
            <br style="box-sizing: inherit;" />
            <span class="tagnamecolor" style="box-sizing: inherit; color: brown;"><span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&lt;</span>script<span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&gt;</span></span><span class="jscolor" style="box-sizing: inherit; color: black;"><br style="box-sizing: inherit;" />
            document.<span class="jspropertycolor" style="box-sizing: inherit; color: black;">write</span>(<span class="jsnumbercolor" style="box-sizing: inherit; color: red;">5</span><span>&nbsp;</span>+<span>&nbsp;</span><span class="jsnumbercolor" style="box-sizing: inherit; color: red;">6</span>);<br style="box-sizing: inherit;" />
            </span><span class="tagnamecolor" style="box-sizing: inherit; color: brown;"><span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&lt;</span>/script<span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&gt;</span></span><br style="box-sizing: inherit;" />
            <br style="box-sizing: inherit;" />
            <span class="tagnamecolor" style="box-sizing: inherit; color: brown;"><span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&lt;</span>/body<span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&gt;</span></span><br style="box-sizing: inherit;" />
            <span class="tagnamecolor" style="box-sizing: inherit; color: brown;"><span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&lt;</span>/html<span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&gt;</span></span></div>
    </div>
    <div class="w3-panel w3-warning" style="box-sizing: inherit; padding: 16px 32px;  background-color: rgb(255, 221, 221); border-left: none; color: rgb(0, 0, 0); font-family: Verdana, sans-serif; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        <p style="box-sizing: inherit; margin-top: 1em; margin-bottom: 1em; font-size: 15px;">
            Using document.write() after an HTML document is loaded, will<span>&nbsp;</span><strong style="box-sizing: inherit; font-weight: bolder;">delete all existing HTML</strong>:</p>
    </div>
    <div class="w3-example" style="box-sizing: inherit; background-color: rgb(241, 241, 241); padding: 8px 20px; margin: 24px -20px; box-shadow: none !important; color: rgb(0, 0, 0); font-family: Verdana, sans-serif; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        <h3 style="box-sizing: inherit; font-size: 24px; font-family: &quot;Segoe UI&quot;, Arial, sans-serif; font-weight: 400; margin: 10px 0px;">Example</h3>
        <div class="w3-code notranslate htmlHigh" style="box-sizing: inherit; font-family: Consolas, &quot;courier new&quot;; font-size: 15px; width: auto; background-color: rgb(255, 255, 255); padding: 8px 12px; border-left: 4px solid rgb(76, 175, 80); overflow-wrap: break-word; margin-top: 16px !important; margin-bottom: 16px !important;">
            <span class="tagnamecolor" style="box-sizing: inherit; color: brown;"><span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&lt;</span>!DOCTYPE<span class="attributecolor" style="box-sizing: inherit; color: red;"><span>&nbsp;</span>html</span><span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&gt;</span></span><br style="box-sizing: inherit;" />
            <span class="tagnamecolor" style="box-sizing: inherit; color: brown;"><span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&lt;</span>html<span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&gt;</span></span><br style="box-sizing: inherit;" />
            <span class="tagnamecolor" style="box-sizing: inherit; color: brown;"><span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&lt;</span>body<span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&gt;</span></span><br style="box-sizing: inherit;" />
            <br style="box-sizing: inherit;" />
            <span class="tagnamecolor" style="box-sizing: inherit; color: brown;"><span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&lt;</span>h1<span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&gt;</span></span>My First Web Page<span class="tagnamecolor" style="box-sizing: inherit; color: brown;"><span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&lt;</span>/h1<span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&gt;</span></span><br style="box-sizing: inherit;" />
            <span class="tagnamecolor" style="box-sizing: inherit; color: brown;"><span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&lt;</span>p<span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&gt;</span></span>My first paragraph.<span class="tagnamecolor" style="box-sizing: inherit; color: brown;"><span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&lt;</span>/p<span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&gt;</span></span><br style="box-sizing: inherit;" />
            <br style="box-sizing: inherit;" />
            <span class="tagnamecolor" style="box-sizing: inherit; color: brown;"><span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&lt;</span>button<span class="attributecolor" style="box-sizing: inherit; color: red;"><span>&nbsp;</span>type<span class="attributevaluecolor" style="box-sizing: inherit; color: mediumblue;">=&quot;button&quot;</span><span>&nbsp;</span>onclick<span class="attributevaluecolor" style="box-sizing: inherit; color: mediumblue;">=&quot;document.write(5 + 6)&quot;</span></span><span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&gt;</span></span>Try it<span class="tagnamecolor" style="box-sizing: inherit; color: brown;"><span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&lt;</span>/button<span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&gt;</span></span><br style="box-sizing: inherit;" />
            <br style="box-sizing: inherit;" />
            <span class="tagnamecolor" style="box-sizing: inherit; color: brown;"><span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&lt;</span>/body<span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&gt;</span></span><br style="box-sizing: inherit;" />
            <span class="tagnamecolor" style="box-sizing: inherit; color: brown;"><span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&lt;</span>/html<span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&gt;</span></span></div>
    </div>
    <span style="color: rgb(0, 0, 0); font-family: Verdana, sans-serif; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 204); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">The document.write() method should only be used for testing.<h2 style="box-sizing: inherit; font-size: 32px; font-family: &quot;Segoe UI&quot;, Arial, sans-serif; font-weight: 400; margin: 10px 0px; color: rgb(0, 0, 0); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        Using window.alert()</h2>
    <p style="box-sizing: inherit; margin-top: 1.2em; margin-bottom: 1.2em; font-size: 15px; color: rgb(0, 0, 0); font-family: Verdana, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        You can use an alert box to display data:</p>
    <div class="w3-example" style="box-sizing: inherit; background-color: rgb(241, 241, 241); padding: 8px 20px; margin: 24px -20px; box-shadow: none !important; color: rgb(0, 0, 0); font-family: Verdana, sans-serif; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        <h3 style="box-sizing: inherit; font-size: 24px; font-family: &quot;Segoe UI&quot;, Arial, sans-serif; font-weight: 400; margin: 10px 0px;">Example</h3>
        <div class="w3-code notranslate htmlHigh" style="box-sizing: inherit; font-family: Consolas, &quot;courier new&quot;; font-size: 15px; width: auto; background-color: rgb(255, 255, 255); padding: 8px 12px; border-left: 4px solid rgb(76, 175, 80); overflow-wrap: break-word; margin-top: 16px !important; margin-bottom: 16px !important;">
            <span class="tagnamecolor" style="box-sizing: inherit; color: brown;"><span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&lt;</span>!DOCTYPE<span class="attributecolor" style="box-sizing: inherit; color: red;"><span>&nbsp;</span>html</span><span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&gt;</span></span><br style="box-sizing: inherit;" />
            <span class="tagnamecolor" style="box-sizing: inherit; color: brown;"><span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&lt;</span>html<span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&gt;</span></span><br style="box-sizing: inherit;" />
            <span class="tagnamecolor" style="box-sizing: inherit; color: brown;"><span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&lt;</span>body<span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&gt;</span></span><br style="box-sizing: inherit;" />
            <br style="box-sizing: inherit;" />
            <span class="tagnamecolor" style="box-sizing: inherit; color: brown;"><span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&lt;</span>h1<span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&gt;</span></span>My First Web Page<span class="tagnamecolor" style="box-sizing: inherit; color: brown;"><span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&lt;</span>/h1<span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&gt;</span></span><br style="box-sizing: inherit;" />
            <span class="tagnamecolor" style="box-sizing: inherit; color: brown;"><span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&lt;</span>p<span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&gt;</span></span>My first paragraph.<span class="tagnamecolor" style="box-sizing: inherit; color: brown;"><span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&lt;</span>/p<span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&gt;</span></span><br style="box-sizing: inherit;" />
            <br style="box-sizing: inherit;" />
            <span class="tagnamecolor" style="box-sizing: inherit; color: brown;"><span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&lt;</span>script<span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&gt;</span></span><span class="jscolor" style="box-sizing: inherit; color: black;"><br style="box-sizing: inherit;" />
            window.<span class="jspropertycolor" style="box-sizing: inherit; color: black;">alert</span>(<span class="jsnumbercolor" style="box-sizing: inherit; color: red;">5</span><span>&nbsp;</span>+<span>&nbsp;</span><span class="jsnumbercolor" style="box-sizing: inherit; color: red;">6</span>);<br style="box-sizing: inherit;" />
            </span><span class="tagnamecolor" style="box-sizing: inherit; color: brown;"><span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&lt;</span>/script<span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&gt;</span></span><br style="box-sizing: inherit;" />
            <br style="box-sizing: inherit;" />
            <span class="tagnamecolor" style="box-sizing: inherit; color: brown;"><span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&lt;</span>/body<span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&gt;</span></span><br style="box-sizing: inherit;" />
            <span class="tagnamecolor" style="box-sizing: inherit; color: brown;"><span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&lt;</span>/html<span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&gt;</span></span></div>
    </div>
    <p style="box-sizing: inherit; margin-top: 1.2em; margin-bottom: 1.2em; font-size: 15px; color: rgb(0, 0, 0); font-family: Verdana, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        You can skip the<span>&nbsp;</span><code class="w3-codespan" style="box-sizing: inherit; font-family: Consolas, &quot;courier new&quot;; font-size: 15.75px; color: crimson; background-color: rgba(222, 222, 222, 0.3); padding-left: 4px; padding-right: 4px;">window</code><span>&nbsp;</span>keyword.</p>
    <p style="box-sizing: inherit; margin-top: 1.2em; margin-bottom: 1.2em; font-size: 15px; color: rgb(0, 0, 0); font-family: Verdana, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        In JavaScript, the window object is the global scope object, that means that variables, properties, and methods by default belong to the window object. This also means that specifying the<span>&nbsp;</span><code class="w3-codespan" style="box-sizing: inherit; font-family: Consolas, &quot;courier new&quot;; font-size: 15.75px; color: crimson; background-color: rgba(222, 222, 222, 0.3); padding-left: 4px; padding-right: 4px;">window</code><span>&nbsp;</span>keyword is optional:</p>
    <div class="w3-example" style="box-sizing: inherit; background-color: rgb(241, 241, 241); padding: 8px 20px; margin: 24px -20px; box-shadow: none !important; color: rgb(0, 0, 0); font-family: Verdana, sans-serif; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        <h3 style="box-sizing: inherit; font-size: 24px; font-family: &quot;Segoe UI&quot;, Arial, sans-serif; font-weight: 400; margin: 10px 0px;">Example</h3>
        <div class="w3-code notranslate htmlHigh" style="box-sizing: inherit; font-family: Consolas, &quot;courier new&quot;; font-size: 15px; width: auto; background-color: rgb(255, 255, 255); padding: 8px 12px; border-left: 4px solid rgb(76, 175, 80); overflow-wrap: break-word; margin-top: 16px !important; margin-bottom: 16px !important;">
            <span class="tagnamecolor" style="box-sizing: inherit; color: brown;"><span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&lt;</span>!DOCTYPE<span class="attributecolor" style="box-sizing: inherit; color: red;"><span>&nbsp;</span>html</span><span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&gt;</span></span><br style="box-sizing: inherit;" />
            <span class="tagnamecolor" style="box-sizing: inherit; color: brown;"><span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&lt;</span>html<span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&gt;</span></span><br style="box-sizing: inherit;" />
            <span class="tagnamecolor" style="box-sizing: inherit; color: brown;"><span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&lt;</span>body<span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&gt;</span></span><br style="box-sizing: inherit;" />
            <br style="box-sizing: inherit;" />
            <span class="tagnamecolor" style="box-sizing: inherit; color: brown;"><span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&lt;</span>h1<span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&gt;</span></span>My First Web Page<span class="tagnamecolor" style="box-sizing: inherit; color: brown;"><span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&lt;</span>/h1<span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&gt;</span></span><br style="box-sizing: inherit;" />
            <span class="tagnamecolor" style="box-sizing: inherit; color: brown;"><span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&lt;</span>p<span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&gt;</span></span>My first paragraph.<span class="tagnamecolor" style="box-sizing: inherit; color: brown;"><span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&lt;</span>/p<span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&gt;</span></span><br style="box-sizing: inherit;" />
            <br style="box-sizing: inherit;" />
            <span class="tagnamecolor" style="box-sizing: inherit; color: brown;"><span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&lt;</span>script<span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&gt;</span></span><span class="jscolor" style="box-sizing: inherit; color: black;"><br style="box-sizing: inherit;" />
            alert(<span class="jsnumbercolor" style="box-sizing: inherit; color: red;">5</span><span>&nbsp;</span>+<span>&nbsp;</span><span class="jsnumbercolor" style="box-sizing: inherit; color: red;">6</span>);<br style="box-sizing: inherit;" />
            </span><span class="tagnamecolor" style="box-sizing: inherit; color: brown;"><span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&lt;</span>/script<span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&gt;</span></span><br style="box-sizing: inherit;" />
            <br style="box-sizing: inherit;" />
            <span class="tagnamecolor" style="box-sizing: inherit; color: brown;"><span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&lt;</span>/body<span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&gt;</span></span><br style="box-sizing: inherit;" />
            <span class="tagnamecolor" style="box-sizing: inherit; color: brown;"><span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&lt;</span>/html<span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&gt;</span></span></div>
    </div>
    <h2 style="box-sizing: inherit; font-size: 32px; font-family: &quot;Segoe UI&quot;, Arial, sans-serif; font-weight: 400; margin: 10px 0px; color: rgb(0, 0, 0); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Using console.log()</h2>
    <p style="box-sizing: inherit; margin-top: 1.2em; margin-bottom: 1.2em; font-size: 15px; color: rgb(0, 0, 0); font-family: Verdana, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        For debugging purposes, you can call the<span>&nbsp;</span><code class="w3-codespan" style="box-sizing: inherit; font-family: Consolas, &quot;courier new&quot;; font-size: 15.75px; color: crimson; background-color: rgba(222, 222, 222, 0.3); padding-left: 4px; padding-right: 4px;">console.log()</code><span>&nbsp;</span>method in the browser to display data.</p>
    <div class="w3-panel w3-note" style="box-sizing: inherit; padding: 16px 32px;  background-color: rgb(255, 255, 204); border-left: none; color: rgb(0, 0, 0); font-family: Verdana, sans-serif; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        <p style="box-sizing: inherit; margin-top: 1em; margin-bottom: 1em; font-size: 15px;">
            You will learn more about debugging in a later chapter.</p>
    </div>
    <div class="w3-example" style="box-sizing: inherit; background-color: rgb(241, 241, 241); padding: 8px 20px; margin: 24px -20px; box-shadow: none !important; color: rgb(0, 0, 0); font-family: Verdana, sans-serif; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        <h3 style="box-sizing: inherit; font-size: 24px; font-family: &quot;Segoe UI&quot;, Arial, sans-serif; font-weight: 400; margin: 10px 0px;">Example</h3>
        <div class="w3-code notranslate htmlHigh" style="box-sizing: inherit; font-family: Consolas, &quot;courier new&quot;; font-size: 15px; width: auto; background-color: rgb(255, 255, 255); padding: 8px 12px; border-left: 4px solid rgb(76, 175, 80); overflow-wrap: break-word; margin-top: 16px !important; margin-bottom: 16px !important;">
            <span class="tagnamecolor" style="box-sizing: inherit; color: brown;"><span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&lt;</span>!DOCTYPE<span class="attributecolor" style="box-sizing: inherit; color: red;"><span>&nbsp;</span>html</span><span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&gt;</span></span><br style="box-sizing: inherit;" />
            <span class="tagnamecolor" style="box-sizing: inherit; color: brown;"><span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&lt;</span>html<span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&gt;</span></span><br style="box-sizing: inherit;" />
            <span class="tagnamecolor" style="box-sizing: inherit; color: brown;"><span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&lt;</span>body<span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&gt;</span></span><br style="box-sizing: inherit;" />
            <br style="box-sizing: inherit;" />
            <span class="tagnamecolor" style="box-sizing: inherit; color: brown;"><span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&lt;</span>script<span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&gt;</span></span><span class="jscolor" style="box-sizing: inherit; color: black;"><br style="box-sizing: inherit;" />
            console.<span class="jspropertycolor" style="box-sizing: inherit; color: black;">log</span>(<span class="jsnumbercolor" style="box-sizing: inherit; color: red;">5</span><span>&nbsp;</span>+<span>&nbsp;</span><span class="jsnumbercolor" style="box-sizing: inherit; color: red;">6</span>);<br style="box-sizing: inherit;" />
            </span><span class="tagnamecolor" style="box-sizing: inherit; color: brown;"><span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&lt;</span>/script<span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&gt;</span></span><br style="box-sizing: inherit;" />
            <br style="box-sizing: inherit;" />
            <span class="tagnamecolor" style="box-sizing: inherit; color: brown;"><span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&lt;</span>/body<span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&gt;</span></span><br style="box-sizing: inherit;" />
            <span class="tagnamecolor" style="box-sizing: inherit; color: brown;"><span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&lt;</span>/html<span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&gt;</span></span></div>
    </div>
    <h2 style="box-sizing: inherit; font-size: 32px; font-family: &quot;Segoe UI&quot;, Arial, sans-serif; font-weight: 400; margin: 10px 0px; color: rgb(0, 0, 0); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">JavaScript Print</h2>
    <p style="box-sizing: inherit; margin-top: 1.2em; margin-bottom: 1.2em; font-size: 15px; color: rgb(0, 0, 0); font-family: Verdana, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        JavaScript does not have any print object or print methods.</p>
    <p style="box-sizing: inherit; margin-top: 1.2em; margin-bottom: 1.2em; font-size: 15px; color: rgb(0, 0, 0); font-family: Verdana, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        You cannot access output devices from JavaScript.</p>
    <p style="box-sizing: inherit; margin-top: 1.2em; margin-bottom: 1.2em; font-size: 15px; color: rgb(0, 0, 0); font-family: Verdana, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        The only exception is that you can call the<span>&nbsp;</span><code class="w3-codespan" style="box-sizing: inherit; font-family: Consolas, &quot;courier new&quot;; font-size: 15.75px; color: crimson; background-color: rgba(222, 222, 222, 0.3); padding-left: 4px; padding-right: 4px;">window.print()</code><span>&nbsp;</span>method in the browser to print the content of the current window.</p>
    <div class="w3-example" style="box-sizing: inherit; background-color: rgb(241, 241, 241); padding: 8px 20px; margin: 24px -20px; box-shadow: none !important; color: rgb(0, 0, 0); font-family: Verdana, sans-serif; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        <h3 style="box-sizing: inherit; font-size: 24px; font-family: &quot;Segoe UI&quot;, Arial, sans-serif; font-weight: 400; margin: 10px 0px;">Example</h3>
        <div class="w3-code notranslate htmlHigh" style="box-sizing: inherit; font-family: Consolas, &quot;courier new&quot;; font-size: 15px; width: auto; background-color: rgb(255, 255, 255); padding: 8px 12px; border-left: 4px solid rgb(76, 175, 80); overflow-wrap: break-word; margin-top: 16px !important; margin-bottom: 16px !important;">
            <span class="tagnamecolor" style="box-sizing: inherit; color: brown;"><span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&lt;</span>!DOCTYPE<span class="attributecolor" style="box-sizing: inherit; color: red;"><span>&nbsp;</span>html</span><span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&gt;</span></span><br style="box-sizing: inherit;" />
            <span class="tagnamecolor" style="box-sizing: inherit; color: brown;"><span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&lt;</span>html<span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&gt;</span></span><br style="box-sizing: inherit;" />
            <span class="tagnamecolor" style="box-sizing: inherit; color: brown;"><span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&lt;</span>body<span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&gt;</span></span><br style="box-sizing: inherit;" />
            <br style="box-sizing: inherit;" />
            <span class="tagnamecolor" style="box-sizing: inherit; color: brown;"><span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&lt;</span>button<span class="attributecolor" style="box-sizing: inherit; color: red;"><span>&nbsp;</span>onclick<span class="attributevaluecolor" style="box-sizing: inherit; color: mediumblue;">=&quot;window.print()&quot;</span></span><span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&gt;</span></span>Print this page<span class="tagnamecolor" style="box-sizing: inherit; color: brown;"><span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&lt;</span>/button<span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&gt;</span></span><br style="box-sizing: inherit;" />
            <br style="box-sizing: inherit;" />
            <span class="tagnamecolor" style="box-sizing: inherit; color: brown;"><span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&lt;</span>/body<span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&gt;</span></span><br style="box-sizing: inherit;" />
            <span class="tagnamecolor" style="box-sizing: inherit; color: brown;"><span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&lt;</span>/html<span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&gt;</span></span></div>
    </div>
    </span>
</asp:Content>
