<%@ Page Title="" Language="C#" MasterPageFile="~/jQuery.Master" AutoEventWireup="true" CodeBehind="jQuery Set Content and Attributes.aspx.cs" Inherits="Project.jQuery_Set_Content_and_Attributes" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="ContentPlaceHolder2" runat="server">
    <h1 style="box-sizing: inherit; font-size: 42px; font-family: &quot;Segoe UI&quot;, Arial, sans-serif; font-weight: 400; margin: 10px 0px; color: rgb(0, 0, 0); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">jQuery -<span>&nbsp;</span><span class="color_h1" style="box-sizing: inherit;">Set Content and Attributes</span></h1>
</asp:Content>
<asp:Content ID="Content4" ContentPlaceHolderID="ContentPlaceHolder3" runat="server">
    <h2 style="box-sizing: inherit; font-size: 32px; font-family: &quot;Segoe UI&quot;, Arial, sans-serif; font-weight: 400; margin: 10px 0px; color: rgb(0, 0, 0); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Set Content - text(), html(), and val()</h2>
    <p style="box-sizing: inherit; margin-top: 1.2em; margin-bottom: 1.2em; font-size: 15px; color: rgb(0, 0, 0); font-family: Verdana, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        We will use the same three methods from the previous page to<span>&nbsp;</span><b style="box-sizing: inherit; font-weight: bolder;">set content</b>:</p>
    <ul style="box-sizing: inherit; color: rgb(0, 0, 0); font-family: Verdana, sans-serif; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        <li style="box-sizing: inherit;"><code class="w3-codespan" style="box-sizing: inherit; font-family: Consolas, &quot;courier new&quot;; font-size: 15.75px; color: crimson; background-color: rgba(222, 222, 222, 0.3); padding-left: 4px; padding-right: 4px;">text()</code><span>&nbsp;</span>- Sets or returns the text content of selected elements</li>
        <li style="box-sizing: inherit;"><code class="w3-codespan" style="box-sizing: inherit; font-family: Consolas, &quot;courier new&quot;; font-size: 15.75px; color: crimson; background-color: rgba(222, 222, 222, 0.3); padding-left: 4px; padding-right: 4px;">html()</code><span>&nbsp;</span>- Sets or returns the content of selected elements (including HTML markup)</li>
        <li style="box-sizing: inherit;"><code class="w3-codespan" style="box-sizing: inherit; font-family: Consolas, &quot;courier new&quot;; font-size: 15.75px; color: crimson; background-color: rgba(222, 222, 222, 0.3); padding-left: 4px; padding-right: 4px;">val()</code><span>&nbsp;</span>- Sets or returns the value of form fields</li>
    </ul>
    <p style="box-sizing: inherit; margin-top: 1.2em; margin-bottom: 1.2em; font-size: 15px; color: rgb(0, 0, 0); font-family: Verdana, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        The following example demonstrates how to set content with the jQuery<span>&nbsp;</span><code class="w3-codespan" style="box-sizing: inherit; font-family: Consolas, &quot;courier new&quot;; font-size: 15.75px; color: crimson; background-color: rgba(222, 222, 222, 0.3); padding-left: 4px; padding-right: 4px;">text()</code>,<span>&nbsp;</span><code class="w3-codespan" style="box-sizing: inherit; font-family: Consolas, &quot;courier new&quot;; font-size: 15.75px; color: crimson; background-color: rgba(222, 222, 222, 0.3); padding-left: 4px; padding-right: 4px;">html()</code>, and<span>&nbsp;</span><code class="w3-codespan" style="box-sizing: inherit; font-family: Consolas, &quot;courier new&quot;; font-size: 15.75px; color: crimson; background-color: rgba(222, 222, 222, 0.3); padding-left: 4px; padding-right: 4px;">val()</code><span>&nbsp;</span>methods:</p>
    <div class="w3-example" style="box-sizing: inherit; background-color: rgb(241, 241, 241); padding: 8px 20px; margin: 24px -20px; box-shadow: none !important; color: rgb(0, 0, 0); font-family: Verdana, sans-serif; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        <h3 style="box-sizing: inherit; font-size: 24px; font-family: &quot;Segoe UI&quot;, Arial, sans-serif; font-weight: 400; margin: 10px 0px;">Example</h3>
        <div class="w3-code notranslate jsHigh" style="box-sizing: inherit; font-family: Consolas, &quot;courier new&quot;; font-size: 15px; width: auto; background-color: rgb(255, 255, 255); padding: 8px 12px; border-left: 4px solid rgb(76, 175, 80); overflow-wrap: break-word; margin-top: 16px !important; margin-bottom: 16px !important;">
            <span class="jscolor" style="box-sizing: inherit; color: black;">$(<span class="jsstringcolor" style="box-sizing: inherit; color: brown;">&quot;#btn1&quot;</span>).<span class="jspropertycolor" style="box-sizing: inherit; color: black;">click</span>(<span class="jskeywordcolor" style="box-sizing: inherit; color: mediumblue;">function</span>(){<br style="box-sizing: inherit;" />
            <span class="jsnumbercolor" style="box-sizing: inherit; color: red;"></span>&nbsp;&nbsp;$(<span class="jsstringcolor" style="box-sizing: inherit; color: brown;">&quot;#test1&quot;</span>).<span class="jspropertycolor" style="box-sizing: inherit; color: black;">text</span>(<span class="jsstringcolor" style="box-sizing: inherit; color: brown;">&quot;Hello world!&quot;</span>);<br style="box-sizing: inherit;" />
            <span class="jsnumbercolor" style="box-sizing: inherit; color: red;"></span>});<br style="box-sizing: inherit;" />
            $(<span class="jsstringcolor" style="box-sizing: inherit; color: brown;">&quot;#btn2&quot;</span>).<span class="jspropertycolor" style="box-sizing: inherit; color: black;">click</span>(<span class="jskeywordcolor" style="box-sizing: inherit; color: mediumblue;">function</span>(){<br style="box-sizing: inherit;" />
            <span class="jsnumbercolor" style="box-sizing: inherit; color: red;"></span>&nbsp;&nbsp;$(<span class="jsstringcolor" style="box-sizing: inherit; color: brown;">&quot;#test2&quot;</span>).<span class="jspropertycolor" style="box-sizing: inherit; color: black;">html</span>(<span class="jsstringcolor" style="box-sizing: inherit; color: brown;">&quot;&lt;b&gt;Hello world!&lt;/b&gt;&quot;</span>);<br style="box-sizing: inherit;" />
            <span class="jsnumbercolor" style="box-sizing: inherit; color: red;"></span>});<br style="box-sizing: inherit;" />
            $(<span class="jsstringcolor" style="box-sizing: inherit; color: brown;">&quot;#btn3&quot;</span>).<span class="jspropertycolor" style="box-sizing: inherit; color: black;">click</span>(<span class="jskeywordcolor" style="box-sizing: inherit; color: mediumblue;">function</span>(){<br style="box-sizing: inherit;" />
            <span class="jsnumbercolor" style="box-sizing: inherit; color: red;"></span>&nbsp; $(<span class="jsstringcolor" style="box-sizing: inherit; color: brown;">&quot;#test3&quot;</span>).<span class="jspropertycolor" style="box-sizing: inherit; color: black;">val</span>(<span class="jsstringcolor" style="box-sizing: inherit; color: brown;">&quot;Dolly Duck&quot;</span>);<br style="box-sizing: inherit;" />
            <span class="jsnumbercolor" style="box-sizing: inherit; color: red;"></span>});<span class="jsnumbercolor" style="box-sizing: inherit; color: red;"></span></span></div>
    </div>
    <h2 style="box-sizing: inherit; font-size: 32px; font-family: &quot;Segoe UI&quot;, Arial, sans-serif; font-weight: 400; margin: 10px 0px; color: rgb(0, 0, 0); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">A Callback Function for text(), html(), and val()</h2>
    <p style="box-sizing: inherit; margin-top: 1.2em; margin-bottom: 1.2em; font-size: 15px; color: rgb(0, 0, 0); font-family: Verdana, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        All of the three jQuery methods above:<span>&nbsp;</span><code class="w3-codespan" style="box-sizing: inherit; font-family: Consolas, &quot;courier new&quot;; font-size: 15.75px; color: crimson; background-color: rgba(222, 222, 222, 0.3); padding-left: 4px; padding-right: 4px;">text()</code>,<span>&nbsp;</span><code class="w3-codespan" style="box-sizing: inherit; font-family: Consolas, &quot;courier new&quot;; font-size: 15.75px; color: crimson; background-color: rgba(222, 222, 222, 0.3); padding-left: 4px; padding-right: 4px;">html()</code>, and<span>&nbsp;</span><code class="w3-codespan" style="box-sizing: inherit; font-family: Consolas, &quot;courier new&quot;; font-size: 15.75px; color: crimson; background-color: rgba(222, 222, 222, 0.3); padding-left: 4px; padding-right: 4px;">val()</code>, also come with a callback function. The callback function has two parameters: the index of the current element in the list of elements selected and the original (old) value. You then return the string you 
        wish to use as the new value from the function.</p>
    <p style="box-sizing: inherit; margin-top: 1.2em; margin-bottom: 1.2em; font-size: 15px; color: rgb(0, 0, 0); font-family: Verdana, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        The following example demonstrates<span>&nbsp;</span><code class="w3-codespan" style="box-sizing: inherit; font-family: Consolas, &quot;courier new&quot;; font-size: 15.75px; color: crimson; background-color: rgba(222, 222, 222, 0.3); padding-left: 4px; padding-right: 4px;">text()</code><span>&nbsp;</span>and<span>&nbsp;</span><code class="w3-codespan" style="box-sizing: inherit; font-family: Consolas, &quot;courier new&quot;; font-size: 15.75px; color: crimson; background-color: rgba(222, 222, 222, 0.3); padding-left: 4px; padding-right: 4px;">html()</code><span>&nbsp;</span>with a callback function:</p>
    <div class="w3-example" style="box-sizing: inherit; background-color: rgb(241, 241, 241); padding: 8px 20px; margin: 24px -20px; box-shadow: none !important; color: rgb(0, 0, 0); font-family: Verdana, sans-serif; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        <h3 style="box-sizing: inherit; font-size: 24px; font-family: &quot;Segoe UI&quot;, Arial, sans-serif; font-weight: 400; margin: 10px 0px;">Example</h3>
        <div class="w3-code notranslate jsHigh" style="box-sizing: inherit; font-family: Consolas, &quot;courier new&quot;; font-size: 15px; width: auto; background-color: rgb(255, 255, 255); padding: 8px 12px; border-left: 4px solid rgb(76, 175, 80); overflow-wrap: break-word; margin-top: 16px !important; margin-bottom: 16px !important;">
            <span class="jscolor" style="box-sizing: inherit; color: black;">$(<span class="jsstringcolor" style="box-sizing: inherit; color: brown;">&quot;#btn1&quot;</span>).<span class="jspropertycolor" style="box-sizing: inherit; color: black;">click</span>(<span class="jskeywordcolor" style="box-sizing: inherit; color: mediumblue;">function</span>(){<br style="box-sizing: inherit;" />
            <span class="jsnumbercolor" style="box-sizing: inherit; color: red;"></span>&nbsp;&nbsp;$(<span class="jsstringcolor" style="box-sizing: inherit; color: brown;">&quot;#test1&quot;</span>).<span class="jspropertycolor" style="box-sizing: inherit; color: black;">text</span>(<span class="jskeywordcolor" style="box-sizing: inherit; color: mediumblue;">function</span>(i, origText){<br style="box-sizing: inherit;" />
            <span class="jsnumbercolor" style="box-sizing: inherit; color: red;"></span>&nbsp;&nbsp;&nbsp;<span>&nbsp;</span><span class="jskeywordcolor" style="box-sizing: inherit; color: mediumblue;">return</span><span>&nbsp;</span><span class="jsstringcolor" style="box-sizing: inherit; color: brown;">&quot;Old text: &quot;</span><span>&nbsp;</span>+ origText +<span>&nbsp;</span><span class="jsstringcolor" style="box-sizing: inherit; color: brown;">&quot; New text: Hello world!<br style="box-sizing: inherit;" />
            &nbsp;&nbsp;&nbsp;&nbsp;(index: &quot;</span><span>&nbsp;</span>+ i +<span>&nbsp;</span><span class="jsstringcolor" style="box-sizing: inherit; color: brown;">&quot;)&quot;</span>;<br style="box-sizing: inherit;" />
            <span class="jsnumbercolor" style="box-sizing: inherit; color: red;"></span>&nbsp;&nbsp;});<br style="box-sizing: inherit;" />
            <span class="jsnumbercolor" style="box-sizing: inherit; color: red;"></span>});<br style="box-sizing: inherit;" />
            <span class="jsnumbercolor" style="box-sizing: inherit; color: red;"></span>
            <br style="box-sizing: inherit;" />
            $(<span class="jsstringcolor" style="box-sizing: inherit; color: brown;">&quot;#btn2&quot;</span>).<span class="jspropertycolor" style="box-sizing: inherit; color: black;">click</span>(<span class="jskeywordcolor" style="box-sizing: inherit; color: mediumblue;">function</span>(){<br style="box-sizing: inherit;" />
            <span class="jsnumbercolor" style="box-sizing: inherit; color: red;"></span>&nbsp;&nbsp;$(<span class="jsstringcolor" style="box-sizing: inherit; color: brown;">&quot;#test2&quot;</span>).<span class="jspropertycolor" style="box-sizing: inherit; color: black;">html</span>(<span class="jskeywordcolor" style="box-sizing: inherit; color: mediumblue;">function</span>(i, origText){<br style="box-sizing: inherit;" />
            <span class="jsnumbercolor" style="box-sizing: inherit; color: red;"></span>&nbsp;&nbsp;&nbsp;<span>&nbsp;</span><span class="jskeywordcolor" style="box-sizing: inherit; color: mediumblue;">return</span><span>&nbsp;</span><span class="jsstringcolor" style="box-sizing: inherit; color: brown;">&quot;Old html: &quot;</span><span>&nbsp;</span>+ origText +<span>&nbsp;</span><span class="jsstringcolor" style="box-sizing: inherit; color: brown;">&quot; New html: Hello &lt;b&gt;world!&lt;/b&gt;<br style="box-sizing: inherit;" />
            &nbsp;&nbsp;&nbsp; (index: &quot;</span><span>&nbsp;</span>+ i +<span>&nbsp;</span><span class="jsstringcolor" style="box-sizing: inherit; color: brown;">&quot;)&quot;</span>;<br style="box-sizing: inherit;" />
            <span class="jsnumbercolor" style="box-sizing: inherit; color: red;"></span>&nbsp;&nbsp;});<br style="box-sizing: inherit;" />
            <span class="jsnumbercolor" style="box-sizing: inherit; color: red;"></span>});</span></div>
    </div>
</asp:Content>
