<%@ Page Title="" Language="C#" MasterPageFile="~/jQuery.Master" AutoEventWireup="true" CodeBehind="jQuery Dimensions.aspx.cs" Inherits="Project.jQuery_Dimensions" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="ContentPlaceHolder2" runat="server">
    <h1 style="box-sizing: inherit; font-size: 42px; font-family: &quot;Segoe UI&quot;, Arial, sans-serif; font-weight: 400; margin: 10px 0px; color: rgb(0, 0, 0); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">jQuery -<span>&nbsp;</span><span class="color_h1" style="box-sizing: inherit;">Dimensions</span></h1>
</asp:Content>
<asp:Content ID="Content4" ContentPlaceHolderID="ContentPlaceHolder3" runat="server">
    <p class="intro" style="box-sizing: inherit; margin-top: 1.2em; margin-bottom: 1.2em; font-size: 16px; color: rgb(0, 0, 0); font-family: Verdana, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        With jQuery, it is easy to work with the dimensions of elements and browser window.</p>
    <hr style="box-sizing: content-box; height: 0px; overflow: visible; border-width: 1px 0px 0px; border-right-style: initial; border-bottom-style: initial; border-left-style: initial; border-right-color: initial; border-bottom-color: initial; border-left-color: initial; border-image: initial; border-top-style: solid; border-top-color: rgb(238, 238, 238); margin: 20px -16px; color: rgb(0, 0, 0); font-family: Verdana, sans-serif; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;" />
    <h2 style="box-sizing: inherit; font-size: 32px; font-family: &quot;Segoe UI&quot;, Arial, sans-serif; font-weight: 400; margin: 10px 0px; color: rgb(0, 0, 0); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">jQuery Dimension Methods</h2>
    <p style="box-sizing: inherit; margin-top: 1.2em; margin-bottom: 1.2em; font-size: 15px; color: rgb(0, 0, 0); font-family: Verdana, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        jQuery has several important methods for working with dimensions:</p>
    <ul style="box-sizing: inherit; color: rgb(0, 0, 0); font-family: Verdana, sans-serif; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        <li style="box-sizing: inherit;"><code class="w3-codespan" style="box-sizing: inherit; font-family: Consolas, &quot;courier new&quot;; font-size: 15.75px; color: crimson; background-color: rgba(222, 222, 222, 0.3); padding-left: 4px; padding-right: 4px;">width()</code></li>
        <li style="box-sizing: inherit;"><code class="w3-codespan" style="box-sizing: inherit; font-family: Consolas, &quot;courier new&quot;; font-size: 15.75px; color: crimson; background-color: rgba(222, 222, 222, 0.3); padding-left: 4px; padding-right: 4px;">height()</code></li>
        <li style="box-sizing: inherit;"><code class="w3-codespan" style="box-sizing: inherit; font-family: Consolas, &quot;courier new&quot;; font-size: 15.75px; color: crimson; background-color: rgba(222, 222, 222, 0.3); padding-left: 4px; padding-right: 4px;">innerWidth()</code></li>
        <li style="box-sizing: inherit;"><code class="w3-codespan" style="box-sizing: inherit; font-family: Consolas, &quot;courier new&quot;; font-size: 15.75px; color: crimson; background-color: rgba(222, 222, 222, 0.3); padding-left: 4px; padding-right: 4px;">innerHeight()</code></li>
        <li style="box-sizing: inherit;"><code class="w3-codespan" style="box-sizing: inherit; font-family: Consolas, &quot;courier new&quot;; font-size: 15.75px; color: crimson; background-color: rgba(222, 222, 222, 0.3); padding-left: 4px; padding-right: 4px;">outerWidth()</code></li>
        <li style="box-sizing: inherit;"><code class="w3-codespan" style="box-sizing: inherit; font-family: Consolas, &quot;courier new&quot;; font-size: 15.75px; color: crimson; background-color: rgba(222, 222, 222, 0.3); padding-left: 4px; padding-right: 4px;">outerHeight()</code></li>
    </ul>
    <hr style="box-sizing: content-box; height: 0px; overflow: visible; border-width: 1px 0px 0px; border-right-style: initial; border-bottom-style: initial; border-left-style: initial; border-right-color: initial; border-bottom-color: initial; border-left-color: initial; border-image: initial; border-top-style: solid; border-top-color: rgb(238, 238, 238); margin: 20px -16px; color: rgb(0, 0, 0); font-family: Verdana, sans-serif; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;" />
    <h2 style="box-sizing: inherit; font-size: 32px; font-family: &quot;Segoe UI&quot;, Arial, sans-serif; font-weight: 400; margin: 10px 0px; color: rgb(0, 0, 0); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">jQuery Dimensions</h2>
    <p style="box-sizing: inherit; margin-top: 1.2em; margin-bottom: 1.2em; font-size: 15px; color: rgb(0, 0, 0); font-family: Verdana, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; text-align: center;">
        <img alt="jQuery Dimensions" class="w3-image" src="https://www.w3schools.com/jquery/img_jquerydim.gif" style="box-sizing: inherit; border-style: none; vertical-align: middle; max-width: 100%; height: auto;" /></p>
    <hr style="box-sizing: content-box; height: 0px; overflow: visible; border-width: 1px 0px 0px; border-right-style: initial; border-bottom-style: initial; border-left-style: initial; border-right-color: initial; border-bottom-color: initial; border-left-color: initial; border-image: initial; border-top-style: solid; border-top-color: rgb(238, 238, 238); margin: 20px -16px; color: rgb(0, 0, 0); font-family: Verdana, sans-serif; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;" />
    <h2 style="box-sizing: inherit; font-size: 32px; font-family: &quot;Segoe UI&quot;, Arial, sans-serif; font-weight: 400; margin: 10px 0px; color: rgb(0, 0, 0); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">jQuery width() and height() Methods</h2>
    <p style="box-sizing: inherit; margin-top: 1.2em; margin-bottom: 1.2em; font-size: 15px; color: rgb(0, 0, 0); font-family: Verdana, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        The<span>&nbsp;</span><code class="w3-codespan" style="box-sizing: inherit; font-family: Consolas, &quot;courier new&quot;; font-size: 15.75px; color: crimson; background-color: rgba(222, 222, 222, 0.3); padding-left: 4px; padding-right: 4px;">width()</code><span>&nbsp;</span>method sets or returns the width of an element (excludes padding, border and margin).</p>
    <p style="box-sizing: inherit; margin-top: 1.2em; margin-bottom: 1.2em; font-size: 15px; color: rgb(0, 0, 0); font-family: Verdana, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        The<span>&nbsp;</span><code class="w3-codespan" style="box-sizing: inherit; font-family: Consolas, &quot;courier new&quot;; font-size: 15.75px; color: crimson; background-color: rgba(222, 222, 222, 0.3); padding-left: 4px; padding-right: 4px;">height()</code><span>&nbsp;</span>method sets or returns the height of an element (excludes padding, border and margin).</p>
    <p style="box-sizing: inherit; margin-top: 1.2em; margin-bottom: 1.2em; font-size: 15px; color: rgb(0, 0, 0); font-family: Verdana, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        The following example returns the width and height of a specified<span>&nbsp;</span><code class="w3-codespan" style="box-sizing: inherit; font-family: Consolas, &quot;courier new&quot;; font-size: 15.75px; color: crimson; background-color: rgba(222, 222, 222, 0.3); padding-left: 4px; padding-right: 4px;">&lt;div&gt;</code><span>&nbsp;</span>element:</p>
    <div class="w3-example" style="box-sizing: inherit; background-color: rgb(241, 241, 241); padding: 8px 20px; margin: 24px -20px; box-shadow: none !important; color: rgb(0, 0, 0); font-family: Verdana, sans-serif; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        <h3 style="box-sizing: inherit; font-size: 24px; font-family: &quot;Segoe UI&quot;, Arial, sans-serif; font-weight: 400; margin: 10px 0px;">Example</h3>
        <div class="w3-code notranslate jsHigh" style="box-sizing: inherit; font-family: Consolas, &quot;courier new&quot;; font-size: 15px; width: auto; background-color: rgb(255, 255, 255); padding: 8px 12px; border-left: 4px solid rgb(76, 175, 80); overflow-wrap: break-word; margin-top: 16px !important; margin-bottom: 16px !important;">
            <span class="jscolor" style="box-sizing: inherit; color: black;">$(<span class="jsstringcolor" style="box-sizing: inherit; color: brown;">&quot;button&quot;</span>).<span class="jspropertycolor" style="box-sizing: inherit; color: black;">click</span>(<span class="jskeywordcolor" style="box-sizing: inherit; color: mediumblue;">function</span>(){<br style="box-sizing: inherit;" />
            <span class="jsnumbercolor" style="box-sizing: inherit; color: red;"></span>&nbsp;&nbsp;<span class="jskeywordcolor" style="box-sizing: inherit; color: mediumblue;">var</span><span>&nbsp;</span>txt =<span>&nbsp;</span><span class="jsstringcolor" style="box-sizing: inherit; color: brown;">&quot;&quot;</span>;<br style="box-sizing: inherit;" />
            <span class="jsnumbercolor" style="box-sizing: inherit; color: red;"></span>&nbsp;&nbsp;txt +=<span>&nbsp;</span><span class="jsstringcolor" style="box-sizing: inherit; color: brown;">&quot;Width: &quot;</span><span>&nbsp;</span>+ $(<span class="jsstringcolor" style="box-sizing: inherit; color: brown;">&quot;#div1&quot;</span>).<span class="jspropertycolor" style="box-sizing: inherit; color: black;">width</span>() +<span>&nbsp;</span><span class="jsstringcolor" style="box-sizing: inherit; color: brown;">&quot;&lt;/br&gt;&quot;</span>;<br style="box-sizing: inherit;" />
            <span class="jsnumbercolor" style="box-sizing: inherit; color: red;"></span>&nbsp;&nbsp;txt +=<span>&nbsp;</span><span class="jsstringcolor" style="box-sizing: inherit; color: brown;">&quot;Height: &quot;</span><span>&nbsp;</span>+ $(<span class="jsstringcolor" style="box-sizing: inherit; color: brown;">&quot;#div1&quot;</span>).<span class="jspropertycolor" style="box-sizing: inherit; color: black;">height</span>();<br style="box-sizing: inherit;" />
            <span class="jsnumbercolor" style="box-sizing: inherit; color: red;"></span>&nbsp;&nbsp;$(<span class="jsstringcolor" style="box-sizing: inherit; color: brown;">&quot;#div1&quot;</span>).<span class="jspropertycolor" style="box-sizing: inherit; color: black;">html</span>(txt);<br style="box-sizing: inherit;" />
            <span class="jsnumbercolor" style="box-sizing: inherit; color: red;"></span>});</span></div>
    </div>
    <h2 style="box-sizing: inherit; font-size: 32px; font-family: &quot;Segoe UI&quot;, Arial, sans-serif; font-weight: 400; margin: 10px 0px; color: rgb(0, 0, 0); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">jQuery innerWidth() and innerHeight() Methods</h2>
    <p style="box-sizing: inherit; margin-top: 1.2em; margin-bottom: 1.2em; font-size: 15px; color: rgb(0, 0, 0); font-family: Verdana, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        The<span>&nbsp;</span><code class="w3-codespan" style="box-sizing: inherit; font-family: Consolas, &quot;courier new&quot;; font-size: 15.75px; color: crimson; background-color: rgba(222, 222, 222, 0.3); padding-left: 4px; padding-right: 4px;">innerWidth()</code><span>&nbsp;</span>method returns the width of an element (includes padding).</p>
    <p style="box-sizing: inherit; margin-top: 1.2em; margin-bottom: 1.2em; font-size: 15px; color: rgb(0, 0, 0); font-family: Verdana, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        The<span>&nbsp;</span><code class="w3-codespan" style="box-sizing: inherit; font-family: Consolas, &quot;courier new&quot;; font-size: 15.75px; color: crimson; background-color: rgba(222, 222, 222, 0.3); padding-left: 4px; padding-right: 4px;">innerHeight()</code><span>&nbsp;</span>method returns the height of an element (includes padding).</p>
    <p style="box-sizing: inherit; margin-top: 1.2em; margin-bottom: 1.2em; font-size: 15px; color: rgb(0, 0, 0); font-family: Verdana, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        The following example returns the inner-width/height of a specified<span>&nbsp;</span><code class="w3-codespan" style="box-sizing: inherit; font-family: Consolas, &quot;courier new&quot;; font-size: 15.75px; color: crimson; background-color: rgba(222, 222, 222, 0.3); padding-left: 4px; padding-right: 4px;">&lt;div&gt;</code><span>&nbsp;</span>element:</p>
    <div class="w3-example" style="box-sizing: inherit; background-color: rgb(241, 241, 241); padding: 8px 20px; margin: 24px -20px; box-shadow: none !important; color: rgb(0, 0, 0); font-family: Verdana, sans-serif; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        <h3 style="box-sizing: inherit; font-size: 24px; font-family: &quot;Segoe UI&quot;, Arial, sans-serif; font-weight: 400; margin: 10px 0px;">Example</h3>
        <div class="w3-code notranslate jsHigh" style="box-sizing: inherit; font-family: Consolas, &quot;courier new&quot;; font-size: 15px; width: auto; background-color: rgb(255, 255, 255); padding: 8px 12px; border-left: 4px solid rgb(76, 175, 80); overflow-wrap: break-word; margin-top: 16px !important; margin-bottom: 16px !important;">
            <span class="jscolor" style="box-sizing: inherit; color: black;">$(<span class="jsstringcolor" style="box-sizing: inherit; color: brown;">&quot;button&quot;</span>).<span class="jspropertycolor" style="box-sizing: inherit; color: black;">click</span>(<span class="jskeywordcolor" style="box-sizing: inherit; color: mediumblue;">function</span>(){<br style="box-sizing: inherit;" />
            <span class="jsnumbercolor" style="box-sizing: inherit; color: red;"></span>&nbsp;<span>&nbsp;</span><span class="jskeywordcolor" style="box-sizing: inherit; color: mediumblue;">var</span><span>&nbsp;</span>txt =<span>&nbsp;</span><span class="jsstringcolor" style="box-sizing: inherit; color: brown;">&quot;&quot;</span>;<br style="box-sizing: inherit;" />
            <span class="jsnumbercolor" style="box-sizing: inherit; color: red;"></span>&nbsp; txt +=<span>&nbsp;</span><span class="jsstringcolor" style="box-sizing: inherit; color: brown;">&quot;Inner width: &quot;</span><span>&nbsp;</span>+ $(<span class="jsstringcolor" style="box-sizing: inherit; color: brown;">&quot;#div1&quot;</span>).<span class="jspropertycolor" style="box-sizing: inherit; color: black;">innerWidth</span>() +<span>&nbsp;</span><span class="jsstringcolor" style="box-sizing: inherit; color: brown;">&quot;&lt;/br&gt;&quot;</span>;<br style="box-sizing: inherit;" />
            <span class="jsnumbercolor" style="box-sizing: inherit; color: red;"></span>&nbsp; txt +=<span>&nbsp;</span><span class="jsstringcolor" style="box-sizing: inherit; color: brown;">&quot;Inner height: &quot;</span><span>&nbsp;</span>+ $(<span class="jsstringcolor" style="box-sizing: inherit; color: brown;">&quot;#div1&quot;</span>).<span class="jspropertycolor" style="box-sizing: inherit; color: black;">innerHeight</span>();<br style="box-sizing: inherit;" />
            <span class="jsnumbercolor" style="box-sizing: inherit; color: red;"></span>&nbsp; $(<span class="jsstringcolor" style="box-sizing: inherit; color: brown;">&quot;#div1&quot;</span>).<span class="jspropertycolor" style="box-sizing: inherit; color: black;">html</span>(txt);<br style="box-sizing: inherit;" />
            <span class="jsnumbercolor" style="box-sizing: inherit; color: red;"></span>});</span></div>
    </div>
    <h2 style="box-sizing: inherit; font-size: 32px; font-family: &quot;Segoe UI&quot;, Arial, sans-serif; font-weight: 400; margin: 10px 0px; color: rgb(0, 0, 0); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">jQuery outerWidth() and outerHeight() Methods</h2>
    <p style="box-sizing: inherit; margin-top: 1.2em; margin-bottom: 1.2em; font-size: 15px; color: rgb(0, 0, 0); font-family: Verdana, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        The<span>&nbsp;</span><code class="w3-codespan" style="box-sizing: inherit; font-family: Consolas, &quot;courier new&quot;; font-size: 15.75px; color: crimson; background-color: rgba(222, 222, 222, 0.3); padding-left: 4px; padding-right: 4px;">outerWidth()</code><span>&nbsp;</span>method returns the width of an element (includes padding and border).</p>
    <p style="box-sizing: inherit; margin-top: 1.2em; margin-bottom: 1.2em; font-size: 15px; color: rgb(0, 0, 0); font-family: Verdana, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        The<span>&nbsp;</span><code class="w3-codespan" style="box-sizing: inherit; font-family: Consolas, &quot;courier new&quot;; font-size: 15.75px; color: crimson; background-color: rgba(222, 222, 222, 0.3); padding-left: 4px; padding-right: 4px;">outerHeight()</code><span>&nbsp;</span>method returns the height of an element (includes padding and border).</p>
    <p style="box-sizing: inherit; margin-top: 1.2em; margin-bottom: 1.2em; font-size: 15px; color: rgb(0, 0, 0); font-family: Verdana, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        The following example returns the outer-width/height of a specified<span>&nbsp;</span><code class="w3-codespan" style="box-sizing: inherit; font-family: Consolas, &quot;courier new&quot;; font-size: 15.75px; color: crimson; background-color: rgba(222, 222, 222, 0.3); padding-left: 4px; padding-right: 4px;">&lt;div&gt;</code><span>&nbsp;</span>element:</p>
    <div class="w3-example" style="box-sizing: inherit; background-color: rgb(241, 241, 241); padding: 8px 20px; margin: 24px -20px; box-shadow: none !important; color: rgb(0, 0, 0); font-family: Verdana, sans-serif; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        <h3 style="box-sizing: inherit; font-size: 24px; font-family: &quot;Segoe UI&quot;, Arial, sans-serif; font-weight: 400; margin: 10px 0px;">Example</h3>
        <div class="w3-code notranslate jsHigh" style="box-sizing: inherit; font-family: Consolas, &quot;courier new&quot;; font-size: 15px; width: auto; background-color: rgb(255, 255, 255); padding: 8px 12px; border-left: 4px solid rgb(76, 175, 80); overflow-wrap: break-word; margin-top: 16px !important; margin-bottom: 16px !important;">
            <span class="jscolor" style="box-sizing: inherit; color: black;">$(<span class="jsstringcolor" style="box-sizing: inherit; color: brown;">&quot;button&quot;</span>).<span class="jspropertycolor" style="box-sizing: inherit; color: black;">click</span>(<span class="jskeywordcolor" style="box-sizing: inherit; color: mediumblue;">function</span>(){<br style="box-sizing: inherit;" />
            <span class="jsnumbercolor" style="box-sizing: inherit; color: red;"></span>&nbsp;<span>&nbsp;</span><span class="jskeywordcolor" style="box-sizing: inherit; color: mediumblue;">var</span><span>&nbsp;</span>txt =<span>&nbsp;</span><span class="jsstringcolor" style="box-sizing: inherit; color: brown;">&quot;&quot;</span>;<br style="box-sizing: inherit;" />
            <span class="jsnumbercolor" style="box-sizing: inherit; color: red;"></span>&nbsp;&nbsp;txt +=<span>&nbsp;</span><span class="jsstringcolor" style="box-sizing: inherit; color: brown;">&quot;Outer width: &quot;</span><span>&nbsp;</span>+ $(<span class="jsstringcolor" style="box-sizing: inherit; color: brown;">&quot;#div1&quot;</span>).<span class="jspropertycolor" style="box-sizing: inherit; color: black;">outerWidth</span>() +<span>&nbsp;</span><span class="jsstringcolor" style="box-sizing: inherit; color: brown;">&quot;&lt;/br&gt;&quot;</span>;<br style="box-sizing: inherit;" />
            <span class="jsnumbercolor" style="box-sizing: inherit; color: red;"></span>&nbsp;&nbsp;txt +=<span>&nbsp;</span><span class="jsstringcolor" style="box-sizing: inherit; color: brown;">&quot;Outer height: &quot;</span><span>&nbsp;</span>+ $(<span class="jsstringcolor" style="box-sizing: inherit; color: brown;">&quot;#div1&quot;</span>).<span class="jspropertycolor" style="box-sizing: inherit; color: black;">outerHeight</span>();<br style="box-sizing: inherit;" />
            <span class="jsnumbercolor" style="box-sizing: inherit; color: red;"></span>&nbsp; $(<span class="jsstringcolor" style="box-sizing: inherit; color: brown;">&quot;#div1&quot;</span>).<span class="jspropertycolor" style="box-sizing: inherit; color: black;">html</span>(txt);<br style="box-sizing: inherit;" />
            <span class="jsnumbercolor" style="box-sizing: inherit; color: red;"></span>});</span></div>
    </div>
    <p style="box-sizing: inherit; margin-top: 1.2em; margin-bottom: 1.2em; font-size: 15px; color: rgb(0, 0, 0); font-family: Verdana, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        The<span>&nbsp;</span><code class="w3-codespan" style="box-sizing: inherit; font-family: Consolas, &quot;courier new&quot;; font-size: 15.75px; color: crimson; background-color: rgba(222, 222, 222, 0.3); padding-left: 4px; padding-right: 4px;">outerWidth(true)</code><span>&nbsp;</span>method returns the width of an element (includes padding, border, and margin).</p>
    <p style="box-sizing: inherit; margin-top: 1.2em; margin-bottom: 1.2em; font-size: 15px; color: rgb(0, 0, 0); font-family: Verdana, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        The<span>&nbsp;</span><code class="w3-codespan" style="box-sizing: inherit; font-family: Consolas, &quot;courier new&quot;; font-size: 15.75px; color: crimson; background-color: rgba(222, 222, 222, 0.3); padding-left: 4px; padding-right: 4px;">outerHeight(true)</code><span>&nbsp;</span>method returns the height of an element (includes padding, border, and margin).</p>
    <div class="w3-example" style="box-sizing: inherit; background-color: rgb(241, 241, 241); padding: 8px 20px; margin: 24px -20px; box-shadow: none !important; color: rgb(0, 0, 0); font-family: Verdana, sans-serif; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        <h3 style="box-sizing: inherit; font-size: 24px; font-family: &quot;Segoe UI&quot;, Arial, sans-serif; font-weight: 400; margin: 10px 0px;">Example</h3>
        <div class="w3-code notranslate jsHigh" style="box-sizing: inherit; font-family: Consolas, &quot;courier new&quot;; font-size: 15px; width: auto; background-color: rgb(255, 255, 255); padding: 8px 12px; border-left: 4px solid rgb(76, 175, 80); overflow-wrap: break-word; margin-top: 16px !important; margin-bottom: 16px !important;">
            <span class="jscolor" style="box-sizing: inherit; color: black;">$(<span class="jsstringcolor" style="box-sizing: inherit; color: brown;">&quot;button&quot;</span>).<span class="jspropertycolor" style="box-sizing: inherit; color: black;">click</span>(<span class="jskeywordcolor" style="box-sizing: inherit; color: mediumblue;">function</span>(){<br style="box-sizing: inherit;" />
            <span class="jsnumbercolor" style="box-sizing: inherit; color: red;"></span>&nbsp;<span>&nbsp;</span><span class="jskeywordcolor" style="box-sizing: inherit; color: mediumblue;">var</span><span>&nbsp;</span>txt =<span>&nbsp;</span><span class="jsstringcolor" style="box-sizing: inherit; color: brown;">&quot;&quot;</span>;<br style="box-sizing: inherit;" />
            <span class="jsnumbercolor" style="box-sizing: inherit; color: red;"></span>&nbsp; txt +=<span>&nbsp;</span><span class="jsstringcolor" style="box-sizing: inherit; color: brown;">&quot;Outer width (+margin): &quot;</span><span>&nbsp;</span>+ $(<span class="jsstringcolor" style="box-sizing: inherit; color: brown;">&quot;#div1&quot;</span>).<span class="jspropertycolor" style="box-sizing: inherit; color: black;">outerWidth</span>(<span class="jskeywordcolor" style="box-sizing: inherit; color: mediumblue;">true</span>) +<span>&nbsp;</span><span class="jsstringcolor" style="box-sizing: inherit; color: brown;">&quot;&lt;/br&gt;&quot;</span>;<br style="box-sizing: inherit;" />
            <span class="jsnumbercolor" style="box-sizing: inherit; color: red;"></span>&nbsp; txt +=<span>&nbsp;</span><span class="jsstringcolor" style="box-sizing: inherit; color: brown;">&quot;Outer height (+margin): &quot;</span><span>&nbsp;</span>+ $(<span class="jsstringcolor" style="box-sizing: inherit; color: brown;">&quot;#div1&quot;</span>).<span class="jspropertycolor" style="box-sizing: inherit; color: black;">outerHeight</span>(<span class="jskeywordcolor" style="box-sizing: inherit; color: mediumblue;">true</span>);<br style="box-sizing: inherit;" />
            <span class="jsnumbercolor" style="box-sizing: inherit; color: red;"></span>&nbsp; $(<span class="jsstringcolor" style="box-sizing: inherit; color: brown;">&quot;#div1&quot;</span>).<span class="jspropertycolor" style="box-sizing: inherit; color: black;">html</span>(txt);<br style="box-sizing: inherit;" />
            <span class="jsnumbercolor" style="box-sizing: inherit; color: red;"></span>});</span></div>
    </div>
    <h2 style="box-sizing: inherit; font-size: 32px; font-family: &quot;Segoe UI&quot;, Arial, sans-serif; font-weight: 400; margin: 10px 0px; color: rgb(0, 0, 0); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">jQuery More width() and height()</h2>
    <p style="box-sizing: inherit; margin-top: 1.2em; margin-bottom: 1.2em; font-size: 15px; color: rgb(0, 0, 0); font-family: Verdana, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        The following example returns the width and height of the document (the HTML document) and window (the browser viewport):</p>
    <div class="w3-example" style="box-sizing: inherit; background-color: rgb(241, 241, 241); padding: 8px 20px; margin: 24px -20px; box-shadow: none !important; color: rgb(0, 0, 0); font-family: Verdana, sans-serif; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        <h3 style="box-sizing: inherit; font-size: 24px; font-family: &quot;Segoe UI&quot;, Arial, sans-serif; font-weight: 400; margin: 10px 0px;">Example</h3>
        <div class="w3-code notranslate jsHigh" style="box-sizing: inherit; font-family: Consolas, &quot;courier new&quot;; font-size: 15px; width: auto; background-color: rgb(255, 255, 255); padding: 8px 12px; border-left: 4px solid rgb(76, 175, 80); overflow-wrap: break-word; margin-top: 16px !important; margin-bottom: 16px !important;">
            <span class="jscolor" style="box-sizing: inherit; color: black;">$(<span class="jsstringcolor" style="box-sizing: inherit; color: brown;">&quot;button&quot;</span>).<span class="jspropertycolor" style="box-sizing: inherit; color: black;">click</span>(<span class="jskeywordcolor" style="box-sizing: inherit; color: mediumblue;">function</span>(){<br style="box-sizing: inherit;" />
            <span class="jsnumbercolor" style="box-sizing: inherit; color: red;"></span>&nbsp;<span>&nbsp;</span><span class="jskeywordcolor" style="box-sizing: inherit; color: mediumblue;">var</span><span>&nbsp;</span>txt =<span>&nbsp;</span><span class="jsstringcolor" style="box-sizing: inherit; color: brown;">&quot;&quot;</span>;<br style="box-sizing: inherit;" />
            <span class="jsnumbercolor" style="box-sizing: inherit; color: red;"></span>&nbsp; txt +=<span>&nbsp;</span><span class="jsstringcolor" style="box-sizing: inherit; color: brown;">&quot;Document width/height: &quot;</span><span>&nbsp;</span>+ $(document).<span class="jspropertycolor" style="box-sizing: inherit; color: black;">width</span>();<br style="box-sizing: inherit;" />
            <span class="jsnumbercolor" style="box-sizing: inherit; color: red;"></span>&nbsp; txt +=<span>&nbsp;</span><span class="jsstringcolor" style="box-sizing: inherit; color: brown;">&quot;x&quot;</span><span>&nbsp;</span>+ $(document).<span class="jspropertycolor" style="box-sizing: inherit; color: black;">height</span>() +<span>&nbsp;</span><span class="jsstringcolor" style="box-sizing: inherit; color: brown;">&quot;\n&quot;</span>;<br style="box-sizing: inherit;" />
            <span class="jsnumbercolor" style="box-sizing: inherit; color: red;"></span>&nbsp;&nbsp;txt +=<span>&nbsp;</span><span class="jsstringcolor" style="box-sizing: inherit; color: brown;">&quot;Window width/height: &quot;</span><span>&nbsp;</span>+ $(window).<span class="jspropertycolor" style="box-sizing: inherit; color: black;">width</span>();<br style="box-sizing: inherit;" />
            <span class="jsnumbercolor" style="box-sizing: inherit; color: red;"></span>&nbsp; txt +=<span>&nbsp;</span><span class="jsstringcolor" style="box-sizing: inherit; color: brown;">&quot;x&quot;</span><span>&nbsp;</span>+ $(window).<span class="jspropertycolor" style="box-sizing: inherit; color: black;">height</span>();<br style="box-sizing: inherit;" />
            <span class="jsnumbercolor" style="box-sizing: inherit; color: red;"></span>&nbsp; alert(txt);<br style="box-sizing: inherit;" />
            <span class="jsnumbercolor" style="box-sizing: inherit; color: red;"></span>});</span></div>
    </div>
    <p style="box-sizing: inherit; margin-top: 1.2em; margin-bottom: 1.2em; font-size: 15px; color: rgb(0, 0, 0); font-family: Verdana, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        The following example sets the width and height of a specified<span>&nbsp;</span><code class="w3-codespan" style="box-sizing: inherit; font-family: Consolas, &quot;courier new&quot;; font-size: 15.75px; color: crimson; background-color: rgba(222, 222, 222, 0.3); padding-left: 4px; padding-right: 4px;">&lt;div&gt;</code><span>&nbsp;</span>element:</p>
    <div class="w3-example" style="box-sizing: inherit; background-color: rgb(241, 241, 241); padding: 8px 20px; margin: 24px -20px; box-shadow: none !important; color: rgb(0, 0, 0); font-family: Verdana, sans-serif; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        <h3 style="box-sizing: inherit; font-size: 24px; font-family: &quot;Segoe UI&quot;, Arial, sans-serif; font-weight: 400; margin: 10px 0px;">Example</h3>
        <div class="w3-code notranslate jsHigh" style="box-sizing: inherit; font-family: Consolas, &quot;courier new&quot;; font-size: 15px; width: auto; background-color: rgb(255, 255, 255); padding: 8px 12px; border-left: 4px solid rgb(76, 175, 80); overflow-wrap: break-word; margin-top: 16px !important; margin-bottom: 16px !important;">
            <span class="jscolor" style="box-sizing: inherit; color: black;">$(<span class="jsstringcolor" style="box-sizing: inherit; color: brown;">&quot;button&quot;</span>).<span class="jspropertycolor" style="box-sizing: inherit; color: black;">click</span>(<span class="jskeywordcolor" style="box-sizing: inherit; color: mediumblue;">function</span>(){<br style="box-sizing: inherit;" />
            <span class="jsnumbercolor" style="box-sizing: inherit; color: red;"></span>&nbsp;&nbsp;$(<span class="jsstringcolor" style="box-sizing: inherit; color: brown;">&quot;#div1&quot;</span>).<span class="jspropertycolor" style="box-sizing: inherit; color: black;">width</span>(<span class="jsnumbercolor" style="box-sizing: inherit; color: red;">500</span>).<span class="jspropertycolor" style="box-sizing: inherit; color: black;">height</span>(<span class="jsnumbercolor" style="box-sizing: inherit; color: red;">500</span>);<br style="box-sizing: inherit;" />
            <span class="jsnumbercolor" style="box-sizing: inherit; color: red;"></span>});</span></div>
    </div>
</asp:Content>
