<%@ Page Title="" Language="C#" MasterPageFile="~/PHP.Master" AutoEventWireup="true" CodeBehind="PHP Comments.aspx.cs" Inherits="Project.PHP_Comments" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="ContentPlaceHolder2" runat="server">
    <h1 style="box-sizing: inherit; font-size: 42px; font-family: &quot;Segoe UI&quot;, Arial, sans-serif; font-weight: 400; margin: 10px 0px; color: rgb(0, 0, 0); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">PHP<span>&nbsp;</span><span class="color_h1" style="box-sizing: inherit;">Comments</span></h1>
</asp:Content>
<asp:Content ID="Content4" ContentPlaceHolderID="ContentPlaceHolder3" runat="server">
    <h2 style="box-sizing: inherit; font-size: 32px; font-family: &quot;Segoe UI&quot;, Arial, sans-serif; font-weight: 400; margin: 10px 0px; color: rgb(0, 0, 0); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Comments in PHP</h2>
    <p style="box-sizing: inherit; margin-top: 1.2em; margin-bottom: 1.2em; font-size: 15px; color: rgb(0, 0, 0); font-family: Verdana, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        A comment in PHP code is a line that is not executed as a part of the program. Its only purpose is to be read by someone who is looking at the code.</p>
    <p style="box-sizing: inherit; margin-top: 1.2em; margin-bottom: 1.2em; font-size: 15px; color: rgb(0, 0, 0); font-family: Verdana, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        Comments can be used to:</p>
    <ul style="box-sizing: inherit; color: rgb(0, 0, 0); font-family: Verdana, sans-serif; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        <li style="box-sizing: inherit;">Let others understand your code</li>
        <li style="box-sizing: inherit;">Remind yourself of what you did - Most programmers have experienced coming back to their own work a year or two later and having to re-figure out what they did. Comments can remind you of what you were thinking when you wrote the code</li>
    </ul>
    <p style="box-sizing: inherit; margin-top: 1.2em; margin-bottom: 1.2em; font-size: 15px; color: rgb(0, 0, 0); font-family: Verdana, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        PHP supports several ways of commenting:</p>
    <div class="w3-example" style="box-sizing: inherit; background-color: rgb(241, 241, 241); padding: 8px 20px; margin: 24px -20px; box-shadow: none !important; color: rgb(0, 0, 0); font-family: Verdana, sans-serif; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        <h3 style="box-sizing: inherit; font-size: 24px; font-family: &quot;Segoe UI&quot;, Arial, sans-serif; font-weight: 400; margin: 10px 0px;">Example</h3>
        <p style="box-sizing: inherit; margin-top: 1em; margin-bottom: 1em; font-size: 15px;">
            Syntax for single-line comments:</p>
        <div class="w3-code htmlHigh notranslate" style="box-sizing: inherit; font-family: Consolas, &quot;courier new&quot;; font-size: 15px; width: auto; background-color: rgb(255, 255, 255); padding: 8px 12px; border-left: 4px solid rgb(76, 175, 80); overflow-wrap: break-word; margin-top: 16px !important; margin-bottom: 16px !important;">
            <span class="tagnamecolor" style="box-sizing: inherit; color: brown;"><span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&lt;</span>!DOCTYPE<span class="attributecolor" style="box-sizing: inherit; color: red;"><span>&nbsp;</span>html</span><span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&gt;</span></span><br style="box-sizing: inherit;" />
            <span class="tagnamecolor" style="box-sizing: inherit; color: brown;"><span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&lt;</span>html<span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&gt;</span></span><br style="box-sizing: inherit;" />
            <span class="tagnamecolor" style="box-sizing: inherit; color: brown;"><span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&lt;</span>body<span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&gt;</span></span><br style="box-sizing: inherit;" />
            <br style="box-sizing: inherit;" />
            <span class="phpcolor" style="box-sizing: inherit; color: black;"><span class="phptagcolor" style="box-sizing: inherit; color: red;">&lt;?php</span><br style="box-sizing: inherit;" />
            <span class="phpnumbercolor" style="box-sizing: inherit; color: red;"></span><span class="commentcolor" style="box-sizing: inherit; color: green;">// This is a single-line comment<br style="box-sizing: inherit;" />
            </span>
            <br style="box-sizing: inherit;" />
            <span class="phpnumbercolor" style="box-sizing: inherit; color: red;"></span><span class="commentcolor" style="box-sizing: inherit; color: green;"># This is also a single-line comment<br style="box-sizing: inherit;" />
            </span><span class="phptagcolor" style="box-sizing: inherit; color: red;">?&gt;</span></span><br style="box-sizing: inherit;" />
            <br style="box-sizing: inherit;" />
            <span class="tagnamecolor" style="box-sizing: inherit; color: brown;"><span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&lt;</span>/body<span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&gt;</span></span><br style="box-sizing: inherit;" />
            <span class="tagnamecolor" style="box-sizing: inherit; color: brown;"><span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&lt;</span>/html<span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&gt;</span></span></div>
    </div>
    <h3 style="box-sizing: inherit; font-size: 24px; font-family: &quot;Segoe UI&quot;, Arial, sans-serif; font-weight: 400; margin: 10px 0px; color: rgb(0, 0, 0); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Example</h3>
    <p style="box-sizing: inherit; margin-top: 1em; margin-bottom: 1em; font-size: 15px; color: rgb(0, 0, 0); font-family: Verdana, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        Syntax for multiple-line comments:</p>
    <div class="w3-code htmlHigh notranslate" style="box-sizing: inherit; font-family: Consolas, &quot;courier new&quot;; font-size: 15px; width: auto; background-color: rgb(255, 255, 255); padding: 8px 12px; border-left: 4px solid rgb(76, 175, 80); overflow-wrap: break-word; margin-top: 16px !important; margin-bottom: 16px !important; color: rgb(0, 0, 0); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        <span class="tagnamecolor" style="box-sizing: inherit; color: brown;"><span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&lt;</span>!DOCTYPE<span class="attributecolor" style="box-sizing: inherit; color: red;"><span>&nbsp;</span>html</span><span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&gt;</span></span><br style="box-sizing: inherit;" />
        <span class="tagnamecolor" style="box-sizing: inherit; color: brown;"><span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&lt;</span>html<span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&gt;</span></span><br style="box-sizing: inherit;" />
        <span class="tagnamecolor" style="box-sizing: inherit; color: brown;"><span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&lt;</span>body<span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&gt;</span></span><br style="box-sizing: inherit;" />
        <br style="box-sizing: inherit;" />
        <span class="phpcolor" style="box-sizing: inherit; color: black;"><span class="phptagcolor" style="box-sizing: inherit; color: red;">&lt;?php</span><br style="box-sizing: inherit;" />
        <span class="phpnumbercolor" style="box-sizing: inherit; color: red;"></span><span class="commentcolor" style="box-sizing: inherit; color: green;">/*<br style="box-sizing: inherit;" />
        This is a multiple-lines comment block<br style="box-sizing: inherit;" />
        that spans over multiple<br style="box-sizing: inherit;" />
        lines<br style="box-sizing: inherit;" />
        */</span><br style="box-sizing: inherit;" />
        <span class="phptagcolor" style="box-sizing: inherit; color: red;">?&gt;</span></span><br style="box-sizing: inherit;" />
        <br style="box-sizing: inherit;" />
        <span class="tagnamecolor" style="box-sizing: inherit; color: brown;"><span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&lt;</span>/body<span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&gt;</span></span><br style="box-sizing: inherit;" />
        <span class="tagnamecolor" style="box-sizing: inherit; color: brown;"><span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&lt;</span>/html<span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&gt;</span></span></div>
    <h3 style="box-sizing: inherit; font-size: 24px; font-family: &quot;Segoe UI&quot;, Arial, sans-serif; font-weight: 400; margin: 10px 0px; color: rgb(0, 0, 0); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Example</h3>
    <p style="box-sizing: inherit; margin-top: 1em; margin-bottom: 1em; font-size: 15px; color: rgb(0, 0, 0); font-family: Verdana, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        Using comments to leave out parts of the code:</p>
    <div class="w3-code htmlHigh notranslate" style="box-sizing: inherit; font-family: Consolas, &quot;courier new&quot;; font-size: 15px; width: auto; background-color: rgb(255, 255, 255); padding: 8px 12px; border-left: 4px solid rgb(76, 175, 80); overflow-wrap: break-word; margin-top: 16px !important; margin-bottom: 16px !important; color: rgb(0, 0, 0); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">
        <span class="tagnamecolor" style="box-sizing: inherit; color: brown;"><span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&lt;</span>!DOCTYPE<span class="attributecolor" style="box-sizing: inherit; color: red;"><span>&nbsp;</span>html</span><span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&gt;</span></span><br style="box-sizing: inherit;" />
        <span class="tagnamecolor" style="box-sizing: inherit; color: brown;"><span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&lt;</span>html<span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&gt;</span></span><br style="box-sizing: inherit;" />
        <span class="tagnamecolor" style="box-sizing: inherit; color: brown;"><span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&lt;</span>body<span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&gt;</span></span><br style="box-sizing: inherit;" />
        <br style="box-sizing: inherit;" />
        <span class="phpcolor" style="box-sizing: inherit; color: black;"><span class="phptagcolor" style="box-sizing: inherit; color: red;">&lt;?php</span><br style="box-sizing: inherit;" />
        <span class="phpnumbercolor" style="box-sizing: inherit; color: red;"></span><span class="commentcolor" style="box-sizing: inherit; color: green;">// You can also use comments to leave out parts of a code line<br style="box-sizing: inherit;" />
        </span>$x =<span>&nbsp;</span><span class="phpnumbercolor" style="box-sizing: inherit; color: red;">5</span><span>&nbsp;</span><span class="commentcolor" style="box-sizing: inherit; color: green;">/* + 15 */</span><span>&nbsp;</span>+<span>&nbsp;</span><span class="phpnumbercolor" style="box-sizing: inherit; color: red;">5</span>;<br style="box-sizing: inherit;" />
        <span class="phpkeywordcolor" style="box-sizing: inherit; color: mediumblue;">echo</span><span>&nbsp;</span>$x;<br style="box-sizing: inherit;" />
        <span class="phptagcolor" style="box-sizing: inherit; color: red;">?&gt;</span></span><br style="box-sizing: inherit;" />
        <br style="box-sizing: inherit;" />
        <span class="tagnamecolor" style="box-sizing: inherit; color: brown;"><span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&lt;</span>/body<span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&gt;</span></span><br style="box-sizing: inherit;" />
        <span class="tagnamecolor" style="box-sizing: inherit; color: brown;"><span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&lt;</span>/html<span class="tagcolor" style="box-sizing: inherit; color: mediumblue;">&gt;</span></span></div>
</asp:Content>
